-- GENERATED by tools/gen_aicommands.py from src/include/commands.h +
-- src/game/chrai.c. Do not edit by hand; re-run the generator.
--
-- AI command helper library for the Lua action-block scripting layer.
-- Every engine AI command is a function here that packs its operands and
-- calls ctx:run, so you can write readable AI instead of raw byte arrays:
--
--   local ai = dofile('scripts/ai.lua')
--   pd.register_ailist(0x0021, function(ctx)
--     ai.set_target_chr(ctx, 0xf6)        -- CHR_TARGET
--     ai.try_attack_stand(ctx, 0x220, 0, 0)
--     return 1                            -- yield this frame
--   end)
--
-- Each wrapper returns ctx:run's break flag. Multi-byte operands are
-- packed big-endian to match the engine. The trailing 'label' arg on
-- goto/if_*/try_* commands is accepted for signature parity but is not a
-- meaningful jump target in synthetic mode -- branch with Lua instead.
-- See docs/aicommands.md for the full per-command reference.

local ai = {}

-- big-endian byte splitters (match mkshort/mkword in src/include/util.h)
local function u16(v) return (v >> 8) & 0xff, v & 0xff end
local function u32(v)
  return (v >> 24) & 0xff, (v >> 16) & 0xff, (v >> 8) & 0xff, v & 0xff
end

ai.OPCODE = {}  -- name -> opcode, for reference / ctx:run fallback

-- 0x0000  Makes the script jump to the next label with the given ID, relative to the current command.
ai.OPCODE["goto_next"] = 0x0000
function ai.goto_next(ctx, label)
  return ctx:run(0x0000, (label) & 0xff)
end

-- 0x0001  Makes the script jump to the first label with the given ID, relative to the start of the current ailist.
ai.OPCODE["goto_first"] = 0x0001
function ai.goto_first(ctx, label)
  return ctx:run(0x0001, (label) & 0xff)
end

-- 0x0002  Defines a label.
ai.OPCODE["label"] = 0x0002
function ai.label(ctx, id)
  return ctx:run(0x0002, (id) & 0xff)
end

-- 0x0003  Pauses the current script and yields execution back to the engine.
ai.OPCODE["yield"] = 0x0003
function ai.yield(ctx)
  return ctx:run(0x0003)
end

-- 0x0004  Marks the end of the ailist.
ai.OPCODE["endlist"] = 0x0004
function ai.endlist(ctx)
  return ctx:run(0x0004)
end

-- 0x0005  Assigns a new ailist to the given chr.
ai.OPCODE["set_ailist"] = 0x0005
function ai.set_ailist(ctx, chr, ailist)
  return ctx:run(0x0005, (chr) & 0xff, u16(ailist))
end

-- 0x0006  Sets the chr's return ailist.
ai.OPCODE["set_returnlist"] = 0x0006
function ai.set_returnlist(ctx, chr, ailist)
  return ctx:run(0x0006, (chr) & 0xff, u16(ailist))
end

-- 0x0007  Sets the list that should be assigned when the chr is shot.
ai.OPCODE["set_shotlist"] = 0x0007
function ai.set_shotlist(ctx, ailist)
  return ctx:run(0x0007, u16(ailist))
end

-- 0x0008  Assigns the chr's return list to their current one.
ai.OPCODE["return"] = 0x0008
function ai.return_(ctx)
  return ctx:run(0x0008)
end

-- 0x0009  Makes the chr stop doing whatever they were doing (eg.
ai.OPCODE["stop_chr"] = 0x0009
function ai.stop_chr(ctx)
  return ctx:run(0x0009)
end

-- 0x000A  Makes the chr begin kneeling.
ai.OPCODE["kneel"] = 0x000A
function ai.kneel(ctx)
  return ctx:run(0x000A)
end

-- 0x000B  Make a chr do an animation.
ai.OPCODE["chr_do_animation"] = 0x000B
function ai.chr_do_animation(ctx, animation, startframe, endframe, chranimflags, timemerge, chr, animspeed)
  return ctx:run(0x000B, u16(animation), u16(startframe), u16(endframe), (chranimflags) & 0xff, (timemerge) & 0xff, (chr) & 0xff, (animspeed) & 0xff)
end

-- 0x000C  Checks if the chr is considered to be idle.
ai.OPCODE["if_chr_idle"] = 0x000C
function ai.if_chr_idle(ctx, label)
  return ctx:run(0x000C, (label) & 0xff)
end

-- 0x000D  Makes the chr raise one hand briefly.
ai.OPCODE["be_surprised_one_hand"] = 0x000D
function ai.be_surprised_one_hand(ctx)
  return ctx:run(0x000D)
end

-- 0x000E  Makes the chr look over their shoulder.
ai.OPCODE["be_surprised_look_around"] = 0x000E
function ai.be_surprised_look_around(ctx)
  return ctx:run(0x000E)
end

-- 0x000F  Attempt to jump sideways.
ai.OPCODE["try_sidestep"] = 0x000F
function ai.try_sidestep(ctx, label)
  return ctx:run(0x000F, (label) & 0xff)
end

-- 0x0010  Attempt to hop sideways.
ai.OPCODE["try_jumpout"] = 0x0010
function ai.try_jumpout(ctx, label)
  return ctx:run(0x0010, (label) & 0xff)
end

-- 0x0011  Attempt to run sideways.
ai.OPCODE["try_run_sideways"] = 0x0011
function ai.try_run_sideways(ctx, label)
  return ctx:run(0x0011, (label) & 0xff)
end

-- 0x0012  Attempt to walk and shoot.
ai.OPCODE["try_attack_walk"] = 0x0012
function ai.try_attack_walk(ctx, label)
  return ctx:run(0x0012, (label) & 0xff)
end

-- 0x0013  Attempt to run and shoot.
ai.OPCODE["try_attack_run"] = 0x0013
function ai.try_attack_run(ctx, label)
  return ctx:run(0x0013, (label) & 0xff)
end

-- 0x0014  Attempt to roll and shoot.
ai.OPCODE["try_attack_roll"] = 0x0014
function ai.try_attack_roll(ctx, label)
  return ctx:run(0x0014, (label) & 0xff)
end

-- 0x0015  Makes the chr attempt to do a standing attack.
ai.OPCODE["try_attack_stand"] = 0x0015
function ai.try_attack_stand(ctx, attackflags, entity_id, label)
  return ctx:run(0x0015, u16(attackflags), u16(entity_id), (label) & 0xff)
end

-- 0x0016  Makes the chr attempt to do a kneeling attack.
ai.OPCODE["try_attack_kneel"] = 0x0016
function ai.try_attack_kneel(ctx, attackflags, entity_id, label)
  return ctx:run(0x0016, u16(attackflags), u16(entity_id), (label) & 0xff)
end

-- 0x0017  Modifies the attackflags for the current attack.
ai.OPCODE["try_modify_attack"] = 0x0017
function ai.try_modify_attack(ctx, attackflags, entity_id, label)
  return ctx:run(0x0017, u16(attackflags), u16(entity_id), (label) & 0xff)
end

-- 0x0018  Makes the chr begin facing the given entity.
ai.OPCODE["try_face_entity"] = 0x0018
function ai.try_face_entity(ctx, attackflags, entity_id, label)
  return ctx:run(0x0018, u16(attackflags), u16(entity_id), (label) & 0xff)
end

-- 0x0019  Damages the chr using the given weapon's stats.
ai.OPCODE["damage_chr"] = 0x0019
function ai.damage_chr(ctx, chr, weapon)
  return ctx:run(0x0019, (chr) & 0xff, (8) & 0xff, (weapon) & 0xff, (0) & 0xff, (0) & 0xff, (0) & 0xff)
end

-- 0x001A  Makes achr damage vchr as if achr shot vchr.
ai.OPCODE["chr_damage_chr"] = 0x001A
function ai.chr_damage_chr(ctx, achr, vchr, hitpart)
  return ctx:run(0x001A, (achr) & 0xff, (vchr) & 0xff, (hitpart) & 0xff)
end

-- 0x001B  Makes the chr consider throwing a grenade, using their grenade probability property.
ai.OPCODE["consider_throwing_grenade"] = 0x001B
function ai.consider_throwing_grenade(ctx, value_1, value_2, label)
  return ctx:run(0x001B, u16(value_1), u16(value_2), (label) & 0xff)
end

-- 0x001C  Makes the chr spawn the given item and drop it immediately.
ai.OPCODE["drop_item"] = 0x001C
function ai.drop_item(ctx, modelnum, weaponnum, label)
  return ctx:run(0x001C, u16(modelnum), (weaponnum) & 0xff, (label) & 0xff)
end

-- 0x001D  Makes the chr jog to the given pad.
ai.OPCODE["jog_to_pad"] = 0x001D
function ai.jog_to_pad(ctx, pad)
  return ctx:run(0x001D, u16(pad))
end

-- 0x001E  Makes the chr go to their pad preset.
ai.OPCODE["go_to_target_pad"] = 0x001E
function ai.go_to_target_pad(ctx, speed)
  return ctx:run(0x001E, (speed) & 0xff)
end

-- 0x001F  Makes the chr walk to the given pad.
ai.OPCODE["walk_to_pad"] = 0x001F
function ai.walk_to_pad(ctx, pad)
  return ctx:run(0x001F, u16(pad))
end

-- 0x0020  Makes the chr run to the given pad.
ai.OPCODE["run_to_pad"] = 0x0020
function ai.run_to_pad(ctx, pad)
  return ctx:run(0x0020, u16(pad))
end

-- 0x0021  Assigns the given path ID to the chr for patrolling.
ai.OPCODE["assign_path"] = 0x0021
function ai.assign_path(ctx, pathid)
  return ctx:run(0x0021, (pathid) & 0xff)
end

-- 0x0022  Makes the chr start patrolling.
ai.OPCODE["start_patrol"] = 0x0022
function ai.start_patrol(ctx)
  return ctx:run(0x0022)
end

-- 0x0023  Checks if the chr is patrolling.
ai.OPCODE["if_patrolling"] = 0x0023
function ai.if_patrolling(ctx, label)
  return ctx:run(0x0023, (label) & 0xff)
end

-- 0x0024  Makes the chr surrender.
ai.OPCODE["surrender"] = 0x0024
function ai.surrender(ctx)
  return ctx:run(0x0024)
end

-- 0x0025  Makes the chr drop their gun and fade out.
ai.OPCODE["drop_gun_and_fade_out"] = 0x0025
function ai.drop_gun_and_fade_out(ctx)
  return ctx:run(0x0025)
end

-- 0x0026  Remove the chr completely.
ai.OPCODE["remove_chr"] = 0x0026
function ai.remove_chr(ctx, chr)
  return ctx:run(0x0026, (chr) & 0xff)
end

-- 0x0027  Makes the chr try to run to an alarm switch and activate it.
ai.OPCODE["try_start_alarm"] = 0x0027
function ai.try_start_alarm(ctx, pad, label)
  return ctx:run(0x0027, u16(pad), (label) & 0xff)
end

-- 0x0028  Activates the alarm.
ai.OPCODE["activate_alarm"] = 0x0028
function ai.activate_alarm(ctx)
  return ctx:run(0x0028)
end

-- 0x0029  Deactivates the alarm.
ai.OPCODE["deactivate_alarm"] = 0x0029
function ai.deactivate_alarm(ctx)
  return ctx:run(0x0029)
end

-- 0x002A  Makes the chr attempt to run 1000 units in the opposite direction to their target, without any pathfinding.
ai.OPCODE["try_run_from_target"] = 0x002A
function ai.try_run_from_target(ctx, label)
  return ctx:run(0x002A, (label) & 0xff)
end

-- 0x002B  Makes the chr attempt to jog to their target.
ai.OPCODE["try_jog_to_target"] = 0x002B
function ai.try_jog_to_target(ctx, label)
  return ctx:run(0x002B, (label) & 0xff)
end

-- 0x002C  Makes the chr attempt to jog to their target.
ai.OPCODE["try_walk_to_target"] = 0x002C
function ai.try_walk_to_target(ctx, label)
  return ctx:run(0x002C, (label) & 0xff)
end

-- 0x002D  Makes the chr attempt to jog to their target.
ai.OPCODE["try_run_to_target"] = 0x002D
function ai.try_run_to_target(ctx, label)
  return ctx:run(0x002D, (label) & 0xff)
end

-- 0x002E  Does nothing due to a bug in the implementation.
ai.OPCODE["try_go_to_cover_prop"] = 0x002E
function ai.try_go_to_cover_prop(ctx, label)
  return ctx:run(0x002E, (label) & 0xff)
end

-- 0x002F  Makes the chr attempt to jog to the given chr.
ai.OPCODE["try_jog_to_chr"] = 0x002F
function ai.try_jog_to_chr(ctx, chr, label)
  return ctx:run(0x002F, (chr) & 0xff, (label) & 0xff)
end

-- 0x0030  Makes the chr attempt to walk to the given chr.
ai.OPCODE["try_walk_to_chr"] = 0x0030
function ai.try_walk_to_chr(ctx, chr, label)
  return ctx:run(0x0030, (chr) & 0xff, (label) & 0xff)
end

-- 0x0031  Makes the chr attempt to run to the given chr.
ai.OPCODE["try_run_to_chr"] = 0x0031
function ai.try_run_to_chr(ctx, chr, label)
  return ctx:run(0x0031, (chr) & 0xff, (label) & 0xff)
end

-- 0x0032  Checks if the chr is doing anything, such as running or animating.
ai.OPCODE["if_chr_stopped"] = 0x0032
function ai.if_chr_stopped(ctx, label)
  return ctx:run(0x0032, (label) & 0xff)
end

-- 0x0033  Checks if the chr is doing their death animation, has finished their death animation or is invalid.
ai.OPCODE["if_chr_dead"] = 0x0033
function ai.if_chr_dead(ctx, chr, label)
  return ctx:run(0x0033, (chr) & 0xff, (label) & 0xff)
end

-- 0x0034  Checks if the chr has finished dying.
ai.OPCODE["if_chr_death_animation_finished"] = 0x0034
function ai.if_chr_death_animation_finished(ctx, chr, label)
  return ctx:run(0x0034, (chr) & 0xff, (label) & 0xff)
end

-- 0x0035  Checks if the chr can see their target.
ai.OPCODE["if_can_see_target"] = 0x0035
function ai.if_can_see_target(ctx, label)
  return ctx:run(0x0035, (label) & 0xff)
end

-- 0x0036  Calls the random number generator.
ai.OPCODE["call_rng"] = 0x0036
function ai.call_rng(ctx)
  return ctx:run(0x0036)
end

-- 0x0037  Checks if the chr's rand property is less than the given value.
ai.OPCODE["if_rand_lt"] = 0x0037
function ai.if_rand_lt(ctx, value, label)
  return ctx:run(0x0037, (value) & 0xff, (label) & 0xff)
end

-- 0x0038  Checks if the chr's rand property is greater than the given value.
ai.OPCODE["if_rand_gt"] = 0x0038
function ai.if_rand_gt(ctx, value, label)
  return ctx:run(0x0038, (value) & 0xff, (label) & 0xff)
end

-- 0x0039  Checks if the alarm is currently sounding.
ai.OPCODE["if_can_hear_alarm"] = 0x0039
function ai.if_can_hear_alarm(ctx, label)
  return ctx:run(0x0039, (label) & 0xff)
end

-- 0x003A  Checks if the alarm is currently sounding.
ai.OPCODE["if_alarm_active"] = 0x003A
function ai.if_alarm_active(ctx, label)
  return ctx:run(0x003A, (label) & 0xff)
end

-- 0x003B  Checks if gas has been released from a gas bottle.
ai.OPCODE["if_gas_active"] = 0x003B
function ai.if_gas_active(ctx, label)
  return ctx:run(0x003B, (label) & 0xff)
end

-- 0x003C  Checks if the chr has heard their target (eg.
ai.OPCODE["if_hears_target"] = 0x003C
function ai.if_hears_target(ctx, label)
  return ctx:run(0x003C, (label) & 0xff)
end

-- 0x003D  Go to label if the chr has witnessed another chr being injured.
ai.OPCODE["if_saw_injury"] = 0x003D
function ai.if_saw_injury(ctx, checktype, label)
  return ctx:run(0x003D, (checktype) & 0xff, (label) & 0xff)
end

-- 0x003E  Go to label if the chr has witnessed another chr dying.
ai.OPCODE["if_saw_death"] = 0x003E
function ai.if_saw_death(ctx, checktype, label)
  return ctx:run(0x003E, (checktype) & 0xff, (label) & 0xff)
end

-- 0x003F  Checks if there is line of sight between the current chr and their target.
ai.OPCODE["if_los_to_target"] = 0x003F
function ai.if_los_to_target(ctx, label)
  return ctx:run(0x003F, (label) & 0xff)
end

-- 0x0040  Checks if the current chr's target is in sight of the current chr, or would be in sight if the target were to move <distance> units left or right in a circle...
ai.OPCODE["if_target_nearly_in_sight"] = 0x0040
function ai.if_target_nearly_in_sight(ctx, distance, label)
  return ctx:run(0x0040, u32(distance), (label) & 0xff)
end

-- 0x0041  Checks if the current chr is in sight of their target, or would be in sight if the current chr were to move <distance> units left or right in a circle around...
ai.OPCODE["if_nearly_in_targets_sight"] = 0x0041
function ai.if_nearly_in_targets_sight(ctx, distance, label)
  return ctx:run(0x0041, u32(distance), (label) & 0xff)
end

-- 0x0042  Checks if the current chr can see their target.
ai.OPCODE["set_pad_preset_to_pad_on_route_to_target"] = 0x0042
function ai.set_pad_preset_to_pad_on_route_to_target(ctx, label)
  return ctx:run(0x0042, (label) & 0xff)
end

-- 0x0043  Checks if the chr saw their target within the last 10 seconds.
ai.OPCODE["if_saw_target_recently"] = 0x0043
function ai.if_saw_target_recently(ctx, label)
  return ctx:run(0x0043, (label) & 0xff)
end

-- 0x0044  Checks if the chr heard their target within the last 10 seconds.
ai.OPCODE["if_heard_target_recently"] = 0x0044
function ai.if_heard_target_recently(ctx, label)
  return ctx:run(0x0044, (label) & 0xff)
end

-- 0x0045  Checks if the chr has line of sight to the given chr.
ai.OPCODE["if_los_to_chr"] = 0x0045
function ai.if_los_to_chr(ctx, chr, label)
  return ctx:run(0x0045, (chr) & 0xff, (label) & 0xff)
end

-- 0x0046  Checks if the chr has never been rendered.
ai.OPCODE["if_never_been_onscreen"] = 0x0046
function ai.if_never_been_onscreen(ctx, label)
  return ctx:run(0x0046, (label) & 0xff)
end

-- 0x0047  Checks if the chr is on any player's screen, either on this tick or on the prev tick.
ai.OPCODE["if_onscreen"] = 0x0047
function ai.if_onscreen(ctx, label)
  return ctx:run(0x0047, (label) & 0xff)
end

-- 0x0048  Checks if the chr's room is onscreen.
ai.OPCODE["if_chr_in_onscreen_room"] = 0x0048
function ai.if_chr_in_onscreen_room(ctx, chr, label)
  return ctx:run(0x0048, (chr) & 0xff, (label) & 0xff)
end

-- 0x0049  Checks if a room is visible.
ai.OPCODE["if_room_onscreen"] = 0x0049
function ai.if_room_onscreen(ctx, room, label)
  return ctx:run(0x0049, u16(room), (label) & 0xff)
end

-- 0x004A  Checks if the chr's target is aiming at them.
ai.OPCODE["if_target_aiming_at_me"] = 0x004A
function ai.if_target_aiming_at_me(ctx, label)
  return ctx:run(0x004A, (label) & 0xff)
end

-- 0x004B  Checks if the chr had a shot nearly hit them.
ai.OPCODE["if_near_miss"] = 0x004B
function ai.if_near_miss(ctx, label)
  return ctx:run(0x004B, (label) & 0xff)
end

-- 0x004C  Checks if the chr has detected evidence that the player has been there.
ai.OPCODE["if_sees_suspicious_item"] = 0x004C
function ai.if_sees_suspicious_item(ctx, label)
  return ctx:run(0x004C, (label) & 0xff)
end

-- 0x004D  Checks if the current chr's target is within a certain angle of the chr's direction.
ai.OPCODE["if_target_in_fov_left"] = 0x004D
function ai.if_target_in_fov_left(ctx, angle, label)
  return ctx:run(0x004D, (angle) & 0xff, (label) & 0xff)
end

-- 0x004E  Check if the current chr is in their target's field of view (FOV).
ai.OPCODE["if_fov_check_with_target"] = 0x004E
function ai.if_fov_check_with_target(ctx, angle, op1, op2, label)
  return ctx:run(0x004E, (angle) & 0xff, (op1) & 0xff, (op2) & 0xff, (label) & 0xff)
end

-- 0x004F  Checks if the current chr's target is outside of a certain angle of the chr's direction.
ai.OPCODE["if_target_out_of_fov_left"] = 0x004F
function ai.if_target_out_of_fov_left(ctx, angle, label)
  return ctx:run(0x004F, (angle) & 0xff, (label) & 0xff)
end

-- 0x0050  Similar to 004d and 004f, but checks if the target is within the angle of the current chr's 12 o'clock (ie.
ai.OPCODE["if_target_in_fov"] = 0x0050
function ai.if_target_in_fov(ctx, angle, label)
  return ctx:run(0x0050, (angle) & 0xff, (label) & 0xff)
end

-- 0x0051  Similar to 004d and 004f, but checks if the target is not in front of the current chr by the given angle.
ai.OPCODE["if_target_out_of_fov"] = 0x0051
function ai.if_target_out_of_fov(ctx, angle, label)
  return ctx:run(0x0051, (angle) & 0xff, (label) & 0xff)
end

-- 0x0052  Checks if the distance from the current chr to their target is less than the given value.
ai.OPCODE["if_distance_to_target_lt"] = 0x0052
function ai.if_distance_to_target_lt(ctx, distance, label)
  return ctx:run(0x0052, u16((distance // 10)), (label) & 0xff)
end

-- 0x0053  Checks if the distance from the current chr to their target is greater than the given value.
ai.OPCODE["if_distance_to_target_gt"] = 0x0053
function ai.if_distance_to_target_gt(ctx, distance, label)
  return ctx:run(0x0053, u16((distance // 10)), (label) & 0xff)
end

-- 0x0054  Checks if the distance from the given chr to the given pad is less than the given value.
ai.OPCODE["if_chr_distance_to_pad_lt"] = 0x0054
function ai.if_chr_distance_to_pad_lt(ctx, chr, distance, pad, label)
  return ctx:run(0x0054, (chr) & 0xff, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x0055  Checks if the distance from the given chr to the given pad is greater than the given value.
ai.OPCODE["if_chr_distance_to_pad_gt"] = 0x0055
function ai.if_chr_distance_to_pad_gt(ctx, chr, distance, pad, label)
  return ctx:run(0x0055, (chr) & 0xff, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x0056  Checks if the distance from the current chr to the given chr is less than the given value.
ai.OPCODE["if_distance_to_chr_lt"] = 0x0056
function ai.if_distance_to_chr_lt(ctx, distance, chr, label)
  return ctx:run(0x0056, u16((distance // 10)), (chr) & 0xff, (label) & 0xff)
end

-- 0x0057  Checks if the distance from the current chr to the given chr is greater than the given value.
ai.OPCODE["if_distance_to_chr_gt"] = 0x0057
function ai.if_distance_to_chr_gt(ctx, distance, chr, label)
  return ctx:run(0x0057, u16((distance // 10)), (chr) & 0xff, (label) & 0xff)
end

-- 0x0058  
ai.OPCODE["cmd0058"] = 0x0058
function ai.cmd0058(ctx, distance, label)
  return ctx:run(0x0058, u16((distance // 10)), (label) & 0xff)
end

-- 0x0059  Checks if the distance from the current chr's target to the given pad is less than the given value.
ai.OPCODE["if_distance_from_target_to_pad_lt"] = 0x0059
function ai.if_distance_from_target_to_pad_lt(ctx, distance, pad, label)
  return ctx:run(0x0059, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x005A  Checks if the distance from the current chr's target to the given pad is greater than the given value.
ai.OPCODE["if_distance_from_target_to_pad_gt"] = 0x005A
function ai.if_distance_from_target_to_pad_gt(ctx, distance, pad, label)
  return ctx:run(0x005A, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x005B  Checks if the chr or their camspy is in the given room.
ai.OPCODE["if_chr_in_room"] = 0x005B
function ai.if_chr_in_room(ctx, chr, type, room_or_pad, label)
  return ctx:run(0x005B, (chr) & 0xff, (type) & 0xff, u16(room_or_pad), (label) & 0xff)
end

-- 0x005C  Checks if the chr's target is in the given room.
ai.OPCODE["if_target_in_room"] = 0x005C
function ai.if_target_in_room(ctx, room, label)
  return ctx:run(0x005C, u16(room), (label) & 0xff)
end

-- 0x005D  Checks if the given chr has the given object in their inventory.
ai.OPCODE["if_chr_has_object"] = 0x005D
function ai.if_chr_has_object(ctx, chr, object, label)
  return ctx:run(0x005D, (chr) & 0xff, (object) & 0xff, (label) & 0xff)
end

-- 0x005E  Checks if the given weapon has been thrown.
ai.OPCODE["if_weapon_thrown"] = 0x005E
function ai.if_weapon_thrown(ctx, weapon, label)
  return ctx:run(0x005E, (weapon) & 0xff, (label) & 0xff)
end

-- 0x005F  Checks if the given weapon has been thrown and has landed on the given object.
ai.OPCODE["if_weapon_thrown_on_object"] = 0x005F
function ai.if_weapon_thrown_on_object(ctx, weapon, object, label)
  return ctx:run(0x005F, (weapon) & 0xff, (object) & 0xff, (label) & 0xff)
end

-- 0x0060  Checks if the chr has the given weapon equipped.
ai.OPCODE["if_chr_weapon_equipped"] = 0x0060
function ai.if_chr_weapon_equipped(ctx, chr, weapon, label)
  return ctx:run(0x0060, (chr) & 0xff, (weapon) & 0xff, (label) & 0xff)
end

-- 0x0061  If behavior is zero, go to label if object exists.
ai.OPCODE["if_gun_unclaimed"] = 0x0061
function ai.if_gun_unclaimed(ctx, object, behavior, label)
  return ctx:run(0x0061, (object) & 0xff, (behavior) & 0xff, (label) & 0xff)
end

-- 0x0062  Checks if the object is in good working order (ie.
ai.OPCODE["if_object_in_good_condition"] = 0x0062
function ai.if_object_in_good_condition(ctx, object, label)
  return ctx:run(0x0062, (object) & 0xff, (label) & 0xff)
end

-- 0x0063  Checks if the object has been activated by the given chr.
ai.OPCODE["if_chr_activated_object"] = 0x0063
function ai.if_chr_activated_object(ctx, chr, object, label)
  return ctx:run(0x0063, (chr) & 0xff, (object) & 0xff, (label) & 0xff)
end

-- 0x0065  Interacts with the given object, as if the player pressed B on it.
ai.OPCODE["obj_interact"] = 0x0065
function ai.obj_interact(ctx, object)
  return ctx:run(0x0065, (object) & 0xff)
end

-- 0x0066  Destroys the given object.
ai.OPCODE["destroy_object"] = 0x0066
function ai.destroy_object(ctx, object)
  return ctx:run(0x0066, (object) & 0xff)
end

-- 0x0067  
ai.OPCODE["cmd0067"] = 0x0067
function ai.cmd0067(ctx, object)
  return ctx:run(0x0067, (object) & 0xff)
end

-- 0x0068  Makes the given chr drop their concealed items.
ai.OPCODE["drop_concealed_items"] = 0x0068
function ai.drop_concealed_items(ctx, chr)
  return ctx:run(0x0068, (chr) & 0xff)
end

-- 0x0069  Makes the given chr drop their weapon.
ai.OPCODE["chr_drop_weapon"] = 0x0069
function ai.chr_drop_weapon(ctx, chr)
  return ctx:run(0x0069, (chr) & 0xff)
end

-- 0x006A  Makes the current chr give their object to the given chr.
ai.OPCODE["give_object_to_chr"] = 0x006A
function ai.give_object_to_chr(ctx, object, chr)
  return ctx:run(0x006A, (object) & 0xff, (chr) & 0xff)
end

-- 0x006B  Moves the object to the given pad.
ai.OPCODE["move_object_to_pad"] = 0x006B
function ai.move_object_to_pad(ctx, object, pad)
  return ctx:run(0x006B, (object) & 0xff, u16(pad))
end

-- 0x006C  Opens the door.
ai.OPCODE["open_door"] = 0x006C
function ai.open_door(ctx, door)
  return ctx:run(0x006C, (door) & 0xff)
end

-- 0x006D  Closes the door.
ai.OPCODE["close_door"] = 0x006D
function ai.close_door(ctx, door)
  return ctx:run(0x006D, (door) & 0xff)
end

-- 0x006E  Checks the state of the current door.
ai.OPCODE["if_door_state"] = 0x006E
function ai.if_door_state(ctx, door, doorstate, label)
  return ctx:run(0x006E, (door) & 0xff, (doorstate) & 0xff, (label) & 0xff)
end

-- 0x006F  Checks if the given object is a door.
ai.OPCODE["if_object_is_door"] = 0x006F
function ai.if_object_is_door(ctx, object, label)
  return ctx:run(0x006F, (object) & 0xff, (label) & 0xff)
end

-- 0x0070  Locks the door by applying the given bitmask to it.
ai.OPCODE["lock_door"] = 0x0070
function ai.lock_door(ctx, door, bits)
  return ctx:run(0x0070, (door) & 0xff, (bits) & 0xff)
end

-- 0x0071  Unsets bits from the door's bitmask.
ai.OPCODE["unlock_door"] = 0x0071
function ai.unlock_door(ctx, door, bits)
  return ctx:run(0x0071, (door) & 0xff, (bits) & 0xff)
end

-- 0x0072  Checks if the door is locked with the given bitmask.
ai.OPCODE["if_door_locked"] = 0x0072
function ai.if_door_locked(ctx, door, bits, label)
  return ctx:run(0x0072, (door) & 0xff, (bits) & 0xff, (label) & 0xff)
end

-- 0x0073  Checks if the given objective index is complete.
ai.OPCODE["if_objective_complete"] = 0x0073
function ai.if_objective_complete(ctx, objective, label)
  return ctx:run(0x0073, (objective) & 0xff, (label) & 0xff)
end

-- 0x0074  Checks if the given objective index is failed.
ai.OPCODE["if_objective_failed"] = 0x0074
function ai.if_objective_failed(ctx, objective, label)
  return ctx:run(0x0074, (objective) & 0xff, (label) & 0xff)
end

-- 0x0075  This is only ever called in a sequence of 4, with u1 values 8, 2, 4, 8 in that order.
ai.OPCODE["try_set_target_pad_to_something"] = 0x0075
function ai.try_set_target_pad_to_something(ctx, u1, label)
  return ctx:run(0x0075, (u1) & 0xff, (label) & 0xff)
end

-- 0x0076  Attempts to find a waypoint within the given quadrant of the current chr's target then sets the chr's padpreset to the given waypoint's pad number.
ai.OPCODE["try_set_padpreset_to_target_quadrant"] = 0x0076
function ai.try_set_padpreset_to_target_quadrant(ctx, quadrant, label)
  return ctx:run(0x0076, (quadrant) & 0xff, (label) & 0xff)
end

-- 0x0077  Checks if the difficulty is less than the given value.
ai.OPCODE["if_difficulty_lt"] = 0x0077
function ai.if_difficulty_lt(ctx, diff, label)
  return ctx:run(0x0077, (diff) & 0xff, (label) & 0xff)
end

-- 0x0078  Checks if the difficulty is greater than the given value.
ai.OPCODE["if_difficulty_gt"] = 0x0078
function ai.if_difficulty_gt(ctx, diff, label)
  return ctx:run(0x0078, (diff) & 0xff, (label) & 0xff)
end

-- 0x0079  Checks if the stage timer is less than the given number of seconds.
ai.OPCODE["if_stage_timer_lt"] = 0x0079
function ai.if_stage_timer_lt(ctx, seconds, label)
  return ctx:run(0x0079, u16(seconds), (label) & 0xff)
end

-- 0x007A  Checks if the stage timer is greater than the given number of seconds.
ai.OPCODE["if_stage_timer_gt"] = 0x007A
function ai.if_stage_timer_gt(ctx, seconds, label)
  return ctx:run(0x007A, u16(seconds), (label) & 0xff)
end

-- 0x007B  Checks if the stage ID is less than the given value.
ai.OPCODE["if_stage_lt"] = 0x007B
function ai.if_stage_lt(ctx, stage, label)
  return ctx:run(0x007B, (stage) & 0xff, (label) & 0xff)
end

-- 0x007C  Checks if the stage ID is greater than the given value.
ai.OPCODE["if_stage_gt"] = 0x007C
function ai.if_stage_gt(ctx, stage, label)
  return ctx:run(0x007C, (stage) & 0xff, (label) & 0xff)
end

-- 0x007D  Checks if the chr has been shot less than the given number of times.
ai.OPCODE["if_num_times_shot_lt"] = 0x007D
function ai.if_num_times_shot_lt(ctx, value, label)
  return ctx:run(0x007D, (value) & 0xff, (label) & 0xff)
end

-- 0x007E  Checks if the chr has been shot more than the given number of times.
ai.OPCODE["if_num_times_shot_gt"] = 0x007E
function ai.if_num_times_shot_gt(ctx, value, label)
  return ctx:run(0x007E, (value) & 0xff, (label) & 0xff)
end

-- 0x007F  Checks if the chr has had less than the given number of near misses.
ai.OPCODE["if_num_close_arghs_lt"] = 0x007F
function ai.if_num_close_arghs_lt(ctx, value, label)
  return ctx:run(0x007F, (value) & 0xff, (label) & 0xff)
end

-- 0x0080  Checks if the chr has had more than the given number of near misses.
ai.OPCODE["if_num_close_arghs_gt"] = 0x0080
function ai.if_num_close_arghs_gt(ctx, value, label)
  return ctx:run(0x0080, (value) & 0xff, (label) & 0xff)
end

-- 0x0081  Checks if the chr's health is greater than the given value.
ai.OPCODE["if_chr_health_gt"] = 0x0081
function ai.if_chr_health_gt(ctx, chr, health, label)
  return ctx:run(0x0081, (chr) & 0xff, (health) & 0xff, (label) & 0xff)
end

-- 0x0082  Checks if the chr's health is less than the given value.
ai.OPCODE["if_chr_health_lt"] = 0x0082
function ai.if_chr_health_lt(ctx, chr, health, label)
  return ctx:run(0x0082, (chr) & 0xff, (health) & 0xff, (label) & 0xff)
end

-- 0x0083  Checks if the chr was just injured.
ai.OPCODE["if_just_injured"] = 0x0083
function ai.if_just_injured(ctx, chr, label)
  return ctx:run(0x0083, (chr) & 0xff, (label) & 0xff)
end

-- 0x0084  Sets the current chr's morale to the given value.
ai.OPCODE["set_morale"] = 0x0084
function ai.set_morale(ctx, value)
  return ctx:run(0x0084, (value) & 0xff)
end

-- 0x0085  Adds the given value to the current chr's morale property.
ai.OPCODE["add_morale"] = 0x0085
function ai.add_morale(ctx, value)
  return ctx:run(0x0085, (value) & 0xff)
end

-- 0x0086  Adds the given value to the given chr's morale property.
ai.OPCODE["chr_add_morale"] = 0x0086
function ai.chr_add_morale(ctx, chr, value)
  return ctx:run(0x0086, (chr) & 0xff, (value) & 0xff)
end

-- 0x0087  Subtracts the given value from the current chr's morale property.
ai.OPCODE["subtract_morale"] = 0x0087
function ai.subtract_morale(ctx, value)
  return ctx:run(0x0087, (value) & 0xff)
end

-- 0x0088  Checks if the chr's morale property is less than the given value.
ai.OPCODE["if_morale_lt"] = 0x0088
function ai.if_morale_lt(ctx, value, label)
  return ctx:run(0x0088, (value) & 0xff, (label) & 0xff)
end

-- 0x0089  Checks if the chr's morale property is less than the chr's rand property.
ai.OPCODE["if_morale_lt_random"] = 0x0089
function ai.if_morale_lt_random(ctx, label)
  return ctx:run(0x0089, (label) & 0xff)
end

-- 0x008A  Sets the chr's alertness value.
ai.OPCODE["set_alertness"] = 0x008A
function ai.set_alertness(ctx, value)
  return ctx:run(0x008A, (value) & 0xff)
end

-- 0x008B  Adds the given value to the current chr's alertness.
ai.OPCODE["increase_self_alertness"] = 0x008B
function ai.increase_self_alertness(ctx, value)
  return ctx:run(0x008B, (value) & 0xff)
end

-- 0x008C  Adds the given value to the given chr's alertness.
ai.OPCODE["increase_chr_alertness"] = 0x008C
function ai.increase_chr_alertness(ctx, value, chr)
  return ctx:run(0x008C, (value) & 0xff, (chr) & 0xff)
end

-- 0x008D  Subtracts the given value from current chr's alertness.
ai.OPCODE["subtract_alertness"] = 0x008D
function ai.subtract_alertness(ctx, value, chr)
  return ctx:run(0x008D, (value) & 0xff, (chr) & 0xff)
end

-- 0x008E  Checks if the current chr's alertness is less or more than the given value.
ai.OPCODE["if_alertness"] = 0x008E
function ai.if_alertness(ctx, value, operator, label)
  return ctx:run(0x008E, (value) & 0xff, (operator) & 0xff, (label) & 0xff)
end

-- 0x008F  Checks if the given chr's alertness is less than the given value.
ai.OPCODE["if_chr_alertness_lt"] = 0x008F
function ai.if_chr_alertness_lt(ctx, value, chr, label)
  return ctx:run(0x008F, (value) & 0xff, (chr) & 0xff, (label) & 0xff)
end

-- 0x0090  Checks if the current chr's alertness is less than their rand property.
ai.OPCODE["if_alertness_lt_random"] = 0x0090
function ai.if_alertness_lt_random(ctx, label)
  return ctx:run(0x0090, (label) & 0xff)
end

-- 0x0091  
ai.OPCODE["noop0091"] = 0x0091
function ai.noop0091(ctx)
  return ctx:run(0x0091)
end

-- 0x0092  Set the current chr's hear distance.
ai.OPCODE["set_hear_distance"] = 0x0092
function ai.set_hear_distance(ctx, value)
  return ctx:run(0x0092, u16(value))
end

-- 0x0093  Set the current chr's view distance.
ai.OPCODE["set_view_distance"] = 0x0093
function ai.set_view_distance(ctx, value)
  return ctx:run(0x0093, (value) & 0xff)
end

-- 0x0094  Set the current chr's grenade probability.
ai.OPCODE["set_grenade_probability_out_of_255"] = 0x0094
function ai.set_grenade_probability_out_of_255(ctx, value)
  return ctx:run(0x0094, (value) & 0xff)
end

-- 0x0095  Assigns a new ID to the chr.
ai.OPCODE["set_chr_id"] = 0x0095
function ai.set_chr_id(ctx, newid)
  return ctx:run(0x0095, (newid) & 0xff)
end

-- 0x0096  Sets the limit of how much health a chr or chopper can take before they die.
ai.OPCODE["set_chr_maxdamage"] = 0x0096
function ai.set_chr_maxdamage(ctx, chr, value)
  return ctx:run(0x0096, (chr) & 0xff, u16(value))
end

-- 0x0097  Easy to understand, but technically incorrect explanation: Adds health to the chr.
ai.OPCODE["add_health_or_armor"] = 0x0097
function ai.add_health_or_armor(ctx, value)
  return ctx:run(0x0097, u16(value))
end

-- 0x0098  Set the chr's reaction speed.
ai.OPCODE["set_reaction_speed"] = 0x0098
function ai.set_reaction_speed(ctx, value)
  return ctx:run(0x0098, (value) & 0xff)
end

-- 0x0099  Set the chr's injury recovery speed.
ai.OPCODE["set_recovery_speed"] = 0x0099
function ai.set_recovery_speed(ctx, value)
  return ctx:run(0x0099, (value) & 0xff)
end

-- 0x009A  Set the chr's accuracy.
ai.OPCODE["set_accuracy"] = 0x009A
function ai.set_accuracy(ctx, value)
  return ctx:run(0x009A, (value) & 0xff)
end

-- 0x009B  Sets a flag on the current chr's flags or flags2 property.
ai.OPCODE["set_self_flag_bankx"] = 0x009B
function ai.set_self_flag_bankx(ctx, flag, bank)
  return ctx:run(0x009B, u32(flag), (bank) & 0xff)
end

-- 0x009C  Sets a flag on the current chr's flags or flags2 property.
ai.OPCODE["unset_self_flag_bankx"] = 0x009C
function ai.unset_self_flag_bankx(ctx, flag, bank)
  return ctx:run(0x009C, u32(flag), (bank) & 0xff)
end

-- 0x009D  Checks if the given flag is set on the current chr's flags or flags2 property.
ai.OPCODE["if_self_flag_bankx_eq"] = 0x009D
function ai.if_self_flag_bankx_eq(ctx, flag, bool, bank, label)
  return ctx:run(0x009D, u32(flag), (bool) & 0xff, (bank) & 0xff, (label) & 0xff)
end

-- 0x009E  Sets a flag on the given chr's flags or flags2 property.
ai.OPCODE["set_chr_flag_bankx"] = 0x009E
function ai.set_chr_flag_bankx(ctx, chr, props, bank)
  return ctx:run(0x009E, (chr) & 0xff, u32(props), (bank) & 0xff)
end

-- 0x009F  Unsets a flag on the given chr's flags or flags2 property.
ai.OPCODE["unset_chr_flag_bankx"] = 0x009F
function ai.unset_chr_flag_bankx(ctx, chr, flag, bank)
  return ctx:run(0x009F, (chr) & 0xff, u32(flag), (bank) & 0xff)
end

-- 0x00A0  Checks if the given flag is set on the given chr's flags or flags2 property.
ai.OPCODE["if_chr_has_flag_bankx"] = 0x00A0
function ai.if_chr_has_flag_bankx(ctx, chr, flag, bank, label)
  return ctx:run(0x00A0, (chr) & 0xff, u32(flag), (bank) & 0xff, (label) & 0xff)
end

-- 0x00A1  Sets the given stage flag.
ai.OPCODE["set_stage_flag"] = 0x00A1
function ai.set_stage_flag(ctx, stageflag)
  return ctx:run(0x00A1, u32(stageflag))
end

-- 0x00A2  Unsets the given stage flag.
ai.OPCODE["unset_stage_flag"] = 0x00A2
function ai.unset_stage_flag(ctx, stageflag)
  return ctx:run(0x00A2, u32(stageflag))
end

-- 0x00A3  Checks if the given stage flag is set or not set.
ai.OPCODE["if_stage_flag_eq"] = 0x00A3
function ai.if_stage_flag_eq(ctx, stageflag, bool, label)
  return ctx:run(0x00A3, u32(stageflag), (bool) & 0xff, (label) & 0xff)
end

-- 0x00A4  Sets a flag on the current chr's chrflags property (chr struct offset 0x18).
ai.OPCODE["set_self_chrflag"] = 0x00A4
function ai.set_self_chrflag(ctx, chrflag3)
  return ctx:run(0x00A4, u32(chrflag3))
end

-- 0x00A5  Unsets a flag on the current chr's chrflags property.
ai.OPCODE["unset_self_chrflag"] = 0x00A5
function ai.unset_self_chrflag(ctx, chrflag3)
  return ctx:run(0x00A5, u32(chrflag3))
end

-- 0x00A6  Checks if the current chr has the given chrflag.
ai.OPCODE["if_self_has_chrflag"] = 0x00A6
function ai.if_self_has_chrflag(ctx, chrflag3, label)
  return ctx:run(0x00A6, u32(chrflag3), (label) & 0xff)
end

-- 0x00A7  Sets a flag on the given chr's chrflags property.
ai.OPCODE["set_chr_chrflag"] = 0x00A7
function ai.set_chr_chrflag(ctx, chr, chrflag3)
  return ctx:run(0x00A7, (chr) & 0xff, u32(chrflag3))
end

-- 0x00A8  Unsets a flag on the given chr's chrflags property.
ai.OPCODE["unset_chr_chrflag"] = 0x00A8
function ai.unset_chr_chrflag(ctx, chr, chrflag3)
  return ctx:run(0x00A8, (chr) & 0xff, u32(chrflag3))
end

-- 0x00A9  Checks if the given chr has the given chrflag.
ai.OPCODE["if_chr_has_chrflag"] = 0x00A9
function ai.if_chr_has_chrflag(ctx, chr, chrflag3, label)
  return ctx:run(0x00A9, (chr) & 0xff, u32(chrflag3), (label) & 0xff)
end

-- 0x00AA  Sets a flag on the object's flags property (object struct offset 0x08).
ai.OPCODE["set_object_flag"] = 0x00AA
function ai.set_object_flag(ctx, object, objectflag)
  return ctx:run(0x00AA, (object) & 0xff, u32(objectflag))
end

-- 0x00AB  Unsets a flag on the object's flags property.
ai.OPCODE["unset_object_flag"] = 0x00AB
function ai.unset_object_flag(ctx, object, objectflag)
  return ctx:run(0x00AB, (object) & 0xff, u32(objectflag))
end

-- 0x00AC  Checks if the given object has the given flags property.
ai.OPCODE["if_object_has_flag"] = 0x00AC
function ai.if_object_has_flag(ctx, object, objectflag, label)
  return ctx:run(0x00AC, (object) & 0xff, u32(objectflag), (label) & 0xff)
end

-- 0x00AD  Sets a flag on the object's flags2 property (object struct offset 0x0c).
ai.OPCODE["set_object_flag2"] = 0x00AD
function ai.set_object_flag2(ctx, object, objectflag2)
  return ctx:run(0x00AD, (object) & 0xff, u32(objectflag2))
end

-- 0x00AE  Unsets a flag on the object's flags2 property.
ai.OPCODE["unset_object_flag2"] = 0x00AE
function ai.unset_object_flag2(ctx, object, objectflag2)
  return ctx:run(0x00AE, (object) & 0xff, u32(objectflag2))
end

-- 0x00AF  Checks if the given object has the given flags2 property.
ai.OPCODE["if_object_flag2"] = 0x00AF
function ai.if_object_flag2(ctx, object, objectflag2, label)
  return ctx:run(0x00AF, (object) & 0xff, u32(objectflag2), (label) & 0xff)
end

-- 0x00B0  Sets the current chr's chrpreset property.
ai.OPCODE["set_chrpreset"] = 0x00B0
function ai.set_chrpreset(ctx, chr)
  return ctx:run(0x00B0, (chr) & 0xff)
end

-- 0x00B1  Sets the current chr's target property to the given chr.
ai.OPCODE["set_chr_target_chr"] = 0x00B1
function ai.set_chr_target_chr(ctx, chr, target)
  return ctx:run(0x00B1, (chr) & 0xff, (target) & 0xff)
end

-- 0x00B2  Sets the current chr's padpreset property.
ai.OPCODE["set_padpreset"] = 0x00B2
function ai.set_padpreset(ctx, pad)
  return ctx:run(0x00B2, u16(pad))
end

-- 0x00B3  Sets the given chr's padpreset property.
ai.OPCODE["chr_set_target_pad"] = 0x00B3
function ai.chr_set_target_pad(ctx, chr, pad)
  return ctx:run(0x00B3, (chr) & 0xff, u16(pad))
end

-- 0x00B4  Copies the padpreset from the source chr to the destination chr.
ai.OPCODE["chr_copy_target_pad"] = 0x00B4
function ai.chr_copy_target_pad(ctx, srcchr, dstchr)
  return ctx:run(0x00B4, (srcchr) & 0xff, (dstchr) & 0xff)
end

-- 0x00B5  This command would have printed a message to the developer's console.
ai.OPCODE["dprint"] = 0x00B5
function ai.dprint(ctx)
  return ctx:run(0x00B5)
end

-- 0x00B6  Resets the current chr's timer to zero and starts it.
ai.OPCODE["restart_timer"] = 0x00B6
function ai.restart_timer(ctx)
  return ctx:run(0x00B6)
end

-- 0x00B7  Resets the current chr's timer to zero.
ai.OPCODE["reset_timer"] = 0x00B7
function ai.reset_timer(ctx)
  return ctx:run(0x00B7)
end

-- 0x00B8  Pauses the current chr's timer.
ai.OPCODE["pause_timer"] = 0x00B8
function ai.pause_timer(ctx)
  return ctx:run(0x00B8)
end

-- 0x00B9  Resumes the current chr's timer.
ai.OPCODE["resume_timer"] = 0x00B9
function ai.resume_timer(ctx)
  return ctx:run(0x00B9)
end

-- 0x00BA  Checks if the current chr's timer is stopped.
ai.OPCODE["if_timer_stopped"] = 0x00BA
function ai.if_timer_stopped(ctx, label)
  return ctx:run(0x00BA, (label) & 0xff)
end

-- 0x00BB  Checks if the current chr's timer value is greater than the chr's rand value.
ai.OPCODE["if_timer_gt_random"] = 0x00BB
function ai.if_timer_gt_random(ctx, label)
  return ctx:run(0x00BB, (label) & 0xff)
end

-- 0x00BC  Checks if the current chr's timer value is less than the given value.
ai.OPCODE["if_timer_lt"] = 0x00BC
function ai.if_timer_lt(ctx, value, label)
  return ctx:run(0x00BC, (0) & 0xff, u16(value), (label) & 0xff)
end

-- 0x00BD  Checks if the current chr's timer value is greater than the given value.
ai.OPCODE["if_timer_gt"] = 0x00BD
function ai.if_timer_gt(ctx, value, label)
  return ctx:run(0x00BD, (0) & 0xff, u16(value), (label) & 0xff)
end

-- 0x00BE  Shows the countdown timer.
ai.OPCODE["show_countdown_timer"] = 0x00BE
function ai.show_countdown_timer(ctx)
  return ctx:run(0x00BE)
end

-- 0x00BF  Hides the countdown timer.
ai.OPCODE["hide_countdown_timer"] = 0x00BF
function ai.hide_countdown_timer(ctx)
  return ctx:run(0x00BF)
end

-- 0x00C0  Sets the countdown timer value.
ai.OPCODE["set_countdown_timer"] = 0x00C0
function ai.set_countdown_timer(ctx, seconds)
  return ctx:run(0x00C0, u16(seconds))
end

-- 0x00C1  Stops the countdown timer.
ai.OPCODE["stop_countdown_timer"] = 0x00C1
function ai.stop_countdown_timer(ctx)
  return ctx:run(0x00C1)
end

-- 0x00C2  Starts the countdown timer.
ai.OPCODE["start_countdown_timer"] = 0x00C2
function ai.start_countdown_timer(ctx)
  return ctx:run(0x00C2)
end

-- 0x00C3  Checks if the countdown timer is stopped.
ai.OPCODE["if_countdown_timer_stopped"] = 0x00C3
function ai.if_countdown_timer_stopped(ctx, label)
  return ctx:run(0x00C3, (label) & 0xff)
end

-- 0x00C4  Checks if the countdown timer value is less than the given value.
ai.OPCODE["if_countdown_timer_lt"] = 0x00C4
function ai.if_countdown_timer_lt(ctx, value, label)
  return ctx:run(0x00C4, u16(value), (label) & 0xff)
end

-- 0x00C5  Checks if the countdown timer value is greater than the given value.
ai.OPCODE["if_countdown_timer_gt"] = 0x00C5
function ai.if_countdown_timer_gt(ctx, value, label)
  return ctx:run(0x00C5, u16(value), (label) & 0xff)
end

-- 0x00C6  Attempts to spawn a chr at the given pad.
ai.OPCODE["try_spawn_chr_at_pad"] = 0x00C6
function ai.try_spawn_chr_at_pad(ctx, body, head, pad, ailist, spawnflags, label)
  return ctx:run(0x00C6, (body) & 0xff, (head) & 0xff, u16(pad), u16(ailist), u32(spawnflags), (label) & 0xff)
end

-- 0x00C7  Attempts to spawn a chr at the given chr.
ai.OPCODE["try_spawn_chr_at_chr"] = 0x00C7
function ai.try_spawn_chr_at_chr(ctx, body, head, chrnum, ailist, spawnflags, label)
  return ctx:run(0x00C7, (body) & 0xff, (head) & 0xff, (chrnum) & 0xff, u16(ailist), u32(spawnflags), (label) & 0xff)
end

-- 0x00C8  Makes the chr equip the given weapon.
ai.OPCODE["try_equip_weapon"] = 0x00C8
function ai.try_equip_weapon(ctx, model, weapon, flags, label)
  return ctx:run(0x00C8, u16(model), (weapon) & 0xff, u32(flags), (label) & 0xff)
end

-- 0x00C9  Makes the chr equip the given model as a hat.
ai.OPCODE["try_equip_hat"] = 0x00C9
function ai.try_equip_hat(ctx, model, flags, label)
  return ctx:run(0x00C9, u16(model), u32(flags), (label) & 0xff)
end

-- 0x00CA  
ai.OPCODE["try_spawn_clone2"] = 0x00CA
function ai.try_spawn_clone2(ctx, chr, ailist, spawnflags, label)
  return ctx:run(0x00CA, (chr) & 0xff, u16(ailist), u32(spawnflags), (label) & 0xff)
end

-- 0x00CB  Show a HUD message to the player.
ai.OPCODE["show_hudmsg"] = 0x00CB
function ai.show_hudmsg(ctx, chr, text)
  return ctx:run(0x00CB, (chr) & 0xff, u16(text))
end

-- 0x00CC  Show a HUD message in the top middle of the screen.
ai.OPCODE["show_hudmsg_top_middle"] = 0x00CC
function ai.show_hudmsg_top_middle(ctx, chr, text, color)
  return ctx:run(0x00CC, (chr) & 0xff, u16(text), (color) & 0xff)
end

-- 0x00CD  Makes the given speech play and text appear at the top of the screen.
ai.OPCODE["speak"] = 0x00CD
function ai.speak(ctx, chr, text, sound, channel, color)
  return ctx:run(0x00CD, (chr) & 0xff, u16(text), u16(sound), (channel) & 0xff, (color) & 0xff)
end

-- 0x00CE  Plays the given sound effect.
ai.OPCODE["play_sound"] = 0x00CE
function ai.play_sound(ctx, id, channel)
  return ctx:run(0x00CE, u16(id), (channel) & 0xff)
end

-- 0x00CF  Plays or stops a sound coming from the given object.
ai.OPCODE["set_object_sound_playing"] = 0x00CF
function ai.set_object_sound_playing(ctx, channel, object, bool)
  return ctx:run(0x00CF, (channel) & 0xff, (object) & 0xff, (0) & 0xff, (bool) & 0xff)
end

-- 0x00D0  Plays a sound coming from the given pad.
ai.OPCODE["play_repeating_sound_from_pad"] = 0x00D0
function ai.play_repeating_sound_from_pad(ctx, pad, sound)
  return ctx:run(0x00D0, (0) & 0xff, u16(pad), u16(sound))
end

-- 0x00D1  
ai.OPCODE["set_object_sound_volume"] = 0x00D1
function ai.set_object_sound_volume(ctx, channel, volume, volchangetimer60)
  return ctx:run(0x00D1, (channel) & 0xff, u16(volume), u16(volchangetimer60))
end

-- 0x00D2  
ai.OPCODE["set_object_sound_volume_by_distance"] = 0x00D2
function ai.set_object_sound_volume_by_distance(ctx, channel, distance, volchangetimer60)
  return ctx:run(0x00D2, (channel) & 0xff, u16(distance), u16(volchangetimer60))
end

-- 0x00D3  Stops the given audio channel.
ai.OPCODE["mute_channel"] = 0x00D3
function ai.mute_channel(ctx, channel)
  return ctx:run(0x00D3, (channel) & 0xff)
end

-- 0x00D4  Follows the label if the object's volume is less than the given volume.
ai.OPCODE["if_object_sound_volume_less_than"] = 0x00D4
function ai.if_object_sound_volume_less_than(ctx, channel, volume, label)
  return ctx:run(0x00D4, (channel) & 0xff, u16(volume), (label) & 0xff)
end

-- 0x00D5  Assigns a path to a hovercar and makes it start it.
ai.OPCODE["begin_hovercar_path"] = 0x00D5
function ai.begin_hovercar_path(ctx, path)
  return ctx:run(0x00D5, (path) & 0xff)
end

-- 0x00D6  Sets the hoverbot's speed.
ai.OPCODE["set_vehicle_speed"] = 0x00D6
function ai.set_vehicle_speed(ctx, speed, num_accel_frames)
  return ctx:run(0x00D6, u16(speed), u16(num_accel_frames))
end

-- 0x00D7  Sets the speed of a component of the given vehicle, such as a rotor or wheel.
ai.OPCODE["set_rotor_speed"] = 0x00D7
function ai.set_rotor_speed(ctx, speed, time)
  return ctx:run(0x00D7, u16(speed), u16(time))
end

-- 0x00D8  
ai.OPCODE["noop00d8"] = 0x00D8
function ai.noop00d8(ctx, u1)
  return ctx:run(0x00D8, (u1) & 0xff)
end

-- 0x00D9  
ai.OPCODE["noop00d9"] = 0x00D9
function ai.noop00d9(ctx, u1)
  return ctx:run(0x00D9, (u1) & 0xff)
end

-- 0x00DA  Sets the image for a monitor object.
ai.OPCODE["set_object_image"] = 0x00DA
function ai.set_object_image(ctx, object, slot, image)
  return ctx:run(0x00DA, (object) & 0xff, (slot) & 0xff, (image) & 0xff)
end

-- 0x00DB  
ai.OPCODE["noop00db"] = 0x00DB
function ai.noop00db(ctx, u1)
  return ctx:run(0x00DB, (u1) & 0xff)
end

-- 0x00DC  End the current level immediately.
ai.OPCODE["end_level"] = 0x00DC
function ai.end_level(ctx)
  return ctx:run(0x00DC)
end

-- 0x00DD  
ai.OPCODE["enter_firstperson"] = 0x00DD
function ai.enter_firstperson(ctx)
  return ctx:run(0x00DD)
end

-- 0x00DE  
ai.OPCODE["enter_camera_and_move_to_pad"] = 0x00DE
function ai.enter_camera_and_move_to_pad(ctx, pad)
  return ctx:run(0x00DE, u16(pad))
end

-- 0x00DF  
ai.OPCODE["cmd00df"] = 0x00DF
function ai.cmd00df(ctx, object, u1, u2)
  return ctx:run(0x00DF, (object) & 0xff, u16(u1), u16(u2))
end

-- 0x00E0  Remove control from the given chr.
ai.OPCODE["revoke_control"] = 0x00E0
function ai.revoke_control(ctx, chr, value)
  return ctx:run(0x00E0, (chr) & 0xff, (value) & 0xff)
end

-- 0x00E1  Grant control back to the given chr.
ai.OPCODE["grant_control"] = 0x00E1
function ai.grant_control(ctx, chr)
  return ctx:run(0x00E1, (chr) & 0xff)
end

-- 0x00E2  Attempt to move the chr to the given pad.
ai.OPCODE["chr_move_to_pad"] = 0x00E2
function ai.chr_move_to_pad(ctx, chr, pad, force, label)
  return ctx:run(0x00E2, (chr) & 0xff, u16(pad), (force) & 0xff, (label) & 0xff)
end

-- 0x00E3  
ai.OPCODE["cmd00e3"] = 0x00E3
function ai.cmd00e3(ctx, chr)
  return ctx:run(0x00E3, (chr) & 0xff)
end

-- 0x00E4  
ai.OPCODE["cmd00e4"] = 0x00E4
function ai.cmd00e4(ctx, u1)
  return ctx:run(0x00E4, (u1) & 0xff)
end

-- 0x00E5  
ai.OPCODE["if_colour_fade_complete"] = 0x00E5
function ai.if_colour_fade_complete(ctx, chr, label)
  return ctx:run(0x00E5, (chr) & 0xff, (label) & 0xff)
end

-- 0x00E8  Set the door's state to be fully open.
ai.OPCODE["set_door_open"] = 0x00E8
function ai.set_door_open(ctx, door)
  return ctx:run(0x00E8, (door) & 0xff)
end

-- 0x00E9  
ai.OPCODE["cmd00e9"] = 0x00E9
function ai.cmd00e9(ctx, chr, u1)
  return ctx:run(0x00E9, (chr) & 0xff, (u1) & 0xff)
end

-- 0x00EA  Checks if the number of players is less than the given value.
ai.OPCODE["if_num_human_players_lt"] = 0x00EA
function ai.if_num_human_players_lt(ctx, value, label)
  return ctx:run(0x00EA, (value) & 0xff, (label) & 0xff)
end

-- 0x00EB  Checks if the chr's quantity of ammotype is less than the given value.
ai.OPCODE["if_ammo_quantity_lt"] = 0x00EB
function ai.if_ammo_quantity_lt(ctx, chr, ammotype, value, label)
  return ctx:run(0x00EB, (chr) & 0xff, (ammotype) & 0xff, (value) & 0xff, (label) & 0xff)
end

-- 0x00EC  Makes the player equip the given weapon.
ai.OPCODE["chr_draw_weapon"] = 0x00EC
function ai.chr_draw_weapon(ctx, chr, weapon)
  return ctx:run(0x00EC, (chr) & 0xff, (weapon) & 0xff)
end

-- 0x00ED  Makes the player equip the given weapon (for cutscene use).
ai.OPCODE["chr_draw_weapon_in_cutscene"] = 0x00ED
function ai.chr_draw_weapon_in_cutscene(ctx, chr, weapon)
  return ctx:run(0x00ED, (chr) & 0xff, (weapon) & 0xff)
end

-- 0x00EE  
ai.OPCODE["cmd00ee"] = 0x00EE
function ai.cmd00ee(ctx, chr, x, z)
  return ctx:run(0x00EE, (x) & 0xff, (z) & 0xff)
end

-- 0x00EF  Checks if the given object is in the given room.
ai.OPCODE["if_object_in_room"] = 0x00EF
function ai.if_object_in_room(ctx, object, room, label)
  return ctx:run(0x00EF, (object) & 0xff, u16(room), (label) & 0xff)
end

-- 0x00F0  
ai.OPCODE["cmd00f0"] = 0x00F0
function ai.cmd00f0(ctx, label)
  return ctx:run(0x00F0, (label) & 0xff)
end

-- 0x00F1  Checks if the current chr is attacking.
ai.OPCODE["if_attacking"] = 0x00F1
function ai.if_attacking(ctx, label)
  return ctx:run(0x00F1, (label) & 0xff)
end

-- 0x00F2  Switch to the stage's alternative sky/fog settings.
ai.OPCODE["switch_to_alt_sky"] = 0x00F2
function ai.switch_to_alt_sky(ctx)
  return ctx:run(0x00F2)
end

-- 0x00F3  Makes the given player invincible.
ai.OPCODE["set_invincible"] = 0x00F3
function ai.set_invincible(ctx, chr)
  return ctx:run(0x00F3, (chr) & 0xff)
end

-- 0x00F4  
ai.OPCODE["cmd00f4"] = 0x00F4
function ai.cmd00f4(ctx, u1, u2, u3, u4, u5, u6)
  return ctx:run(0x00F4, u16(u1), u16(u2), u16(u3), u16(u4), u16(u5), u16(u6))
end

-- 0x00F5  
ai.OPCODE["cmd00f5"] = 0x00F5
function ai.cmd00f5(ctx)
  return ctx:run(0x00F5)
end

-- 0x00F6  
ai.OPCODE["cmd00f6"] = 0x00F6
function ai.cmd00f6(ctx, label)
  return ctx:run(0x00F6, (label) & 0xff)
end

-- 0x00F7  Checks if all objectives are complete.
ai.OPCODE["if_all_objectives_complete"] = 0x00F7
function ai.if_all_objectives_complete(ctx, label)
  return ctx:run(0x00F7, (label) & 0xff)
end

-- 0x00F8  Checks if the player is invincible.
ai.OPCODE["if_player_is_invincible"] = 0x00F8
function ai.if_player_is_invincible(ctx, chr, label)
  return ctx:run(0x00F8, (chr) & 0xff, (label) & 0xff)
end

-- 0x00F9  Starts the X music theme.
ai.OPCODE["play_x_track"] = 0x00F9
function ai.play_x_track(ctx, xreason, minsecs, maxsecs)
  return ctx:run(0x00F9, (xreason) & 0xff, (minsecs) & 0xff, (maxsecs) & 0xff)
end

-- 0x00FA  Stops the X music which has the given reason.
ai.OPCODE["stop_x_track"] = 0x00FA
function ai.stop_x_track(ctx, xreason)
  return ctx:run(0x00FA, (xreason) & 0xff)
end

-- 0x00FB  Surround the given player in infinite explosions.
ai.OPCODE["explosions_around_chr"] = 0x00FB
function ai.explosions_around_chr(ctx, chr)
  return ctx:run(0x00FB, (chr) & 0xff)
end

-- 0x00FC  Checks if the player's kill count is greater than the given value.
ai.OPCODE["if_kill_count_gt"] = 0x00FC
function ai.if_kill_count_gt(ctx, value, label)
  return ctx:run(0x00FC, (value) & 0xff, (label) & 0xff)
end

-- 0x00FD  
ai.OPCODE["cmd00fd"] = 0x00FD
function ai.cmd00fd(ctx, chr, label)
  return ctx:run(0x00FD, (chr) & 0xff, (label) & 0xff)
end

-- 0x00FE  Kill Bond/Joanna immediately.
ai.OPCODE["kill_bond"] = 0x00FE
function ai.kill_bond(ctx)
  return ctx:run(0x00FE)
end

-- 0x00FF  Makes the chr raise their hands in a surrendering pose.
ai.OPCODE["be_surprised_surrender"] = 0x00FF
function ai.be_surprised_surrender(ctx)
  return ctx:run(0x00FF)
end

-- 0x0100  
ai.OPCODE["cmd0100_noop"] = 0x0100
function ai.cmd0100_noop(ctx, u1)
  return ctx:run(0x0100, (u1) & 0xff)
end

-- 0x0101  
ai.OPCODE["cmd0101_noop"] = 0x0101
function ai.cmd0101_noop(ctx, u1)
  return ctx:run(0x0101, (u1) & 0xff)
end

-- 0x0102  Modifies the lighting of a room.
ai.OPCODE["set_lights_state"] = 0x0102
function ai.set_lights_state(ctx, roomorpad, operation, to, from, duration60)
  return ctx:run(0x0102, u16(roomorpad), (operation) & 0xff, (to) & 0xff, (from) & 0xff, (duration60) & 0xff, (0) & 0xff, (0) & 0xff, (0) & 0xff)
end

-- 0x0103  Checks if the current chr's proppreset is blocking line of sight from the chr to their target.
ai.OPCODE["if_proppreset_blocking_sight_to_target"] = 0x0103
function ai.if_proppreset_blocking_sight_to_target(ctx, label)
  return ctx:run(0x0103, (label) & 0xff)
end

-- 0x0104  Removes a prop (chr or object) from the stage.
ai.OPCODE["remove_object_at_proppreset"] = 0x0104
function ai.remove_object_at_proppreset(ctx)
  return ctx:run(0x0104)
end

-- 0x0105  Checks if the height (bounding box height, not Y value) of the current chr's proppreset is less than the given value.
ai.OPCODE["if_proppreset_height_lt"] = 0x0105
function ai.if_proppreset_height_lt(ctx, height, label)
  return ctx:run(0x0105, u16(height), (label) & 0xff)
end

-- 0x0106  Set the current chr's target to the given chr.
ai.OPCODE["set_target_chr"] = 0x0106
function ai.set_target_chr(ctx, chr)
  return ctx:run(0x0106, (chr) & 0xff, (0) & 0xff, (0) & 0xff)
end

-- 0x0107  Checks if the current chr's chrpreset's target is different to the current chr's target.
ai.OPCODE["if_chrpresets_target_is_different"] = 0x0107
function ai.if_chrpresets_target_is_different(ctx, label)
  return ctx:run(0x0107, (label) & 0xff)
end

-- 0x0108  If anytarget is false, check if chr1's target is chr2.
ai.OPCODE["if_chr_target_eq"] = 0x0108
function ai.if_chr_target_eq(ctx, chr1, chr2, anytarget, label)
  return ctx:run(0x0108, (chr1) & 0xff, (chr2) & 0xff, (anytarget) & 0xff, (label) & 0xff)
end

-- 0x0109  Check all chrs within the given distance of the current chr.
ai.OPCODE["set_chrpreset_to_chr_near_self"] = 0x0109
function ai.set_chrpreset_to_chr_near_self(ctx, checktype, distance, label)
  return ctx:run(0x0109, (checktype) & 0xff, u16(distance), (label) & 0xff)
end

-- 0x010A  Check all chrs within the given distance of the given pad.
ai.OPCODE["set_chrpreset_to_chr_near_pad"] = 0x010A
function ai.set_chrpreset_to_chr_near_pad(ctx, checktype, distance, padnum, label)
  return ctx:run(0x010A, (checktype) & 0xff, u16((distance // 10)), u16(padnum), (label) & 0xff)
end

-- 0x010B  Set the team that the chr is on.
ai.OPCODE["set_chr_team"] = 0x010B
function ai.set_chr_team(ctx, chr, team)
  return ctx:run(0x010B, (chr) & 0xff, (team) & 0xff)
end

-- 0x010C  Compares the current chr's chrpreset's team with our own.
ai.OPCODE["if_compare_chrpresets_team"] = 0x010C
function ai.if_compare_chrpresets_team(ctx, checktype, label)
  return ctx:run(0x010C, (checktype) & 0xff, (label) & 0xff)
end

-- 0x010D  
ai.OPCODE["noop010d"] = 0x010D
function ai.noop010d(ctx)
  return ctx:run(0x010D)
end

-- 0x010E  Set the shield amount for the current chr.
ai.OPCODE["set_shield"] = 0x010E
function ai.set_shield(ctx, amount)
  return ctx:run(0x010E, u16(amount))
end

-- 0x010F  Checks if the chr's shield amount is less than the given value.
ai.OPCODE["if_chr_shield_lt"] = 0x010F
function ai.if_chr_shield_lt(ctx, chr, value, label)
  return ctx:run(0x010F, (chr) & 0xff, u16(value), (label) & 0xff)
end

-- 0x0110  Checks if the chr's shield amount is greater than the given value.
ai.OPCODE["if_chr_shield_gt"] = 0x0110
function ai.if_chr_shield_gt(ctx, chr, u1, label)
  return ctx:run(0x0110, (chr) & 0xff, u16(u1), (label) & 0xff)
end

-- 0x0111  Begins a camera animation (ie.
ai.OPCODE["camera_movement"] = 0x0111
function ai.camera_movement(ctx, animation)
  return ctx:run(0x0111, u16(animation))
end

-- 0x0112  Makes the given object do the given animation.
ai.OPCODE["object_do_animation"] = 0x0112
function ai.object_do_animation(ctx, animation, object, u2, startframe)
  return ctx:run(0x0112, u16(animation), (object) & 0xff, (u2) & 0xff, u16(startframe))
end

-- 0x0113  Checks if a cutscene is still running.
ai.OPCODE["if_camera_animating"] = 0x0113
function ai.if_camera_animating(ctx, label)
  return ctx:run(0x0113, (label) & 0xff)
end

-- 0x0114  Enables the given chr.
ai.OPCODE["enable_chr"] = 0x0114
function ai.enable_chr(ctx, chr)
  return ctx:run(0x0114, (chr) & 0xff)
end

-- 0x0115  Disables the given chr.
ai.OPCODE["disable_chr"] = 0x0115
function ai.disable_chr(ctx, chr)
  return ctx:run(0x0115, (chr) & 0xff)
end

-- 0x0116  Enables the given object.
ai.OPCODE["enable_object"] = 0x0116
function ai.enable_object(ctx, object)
  return ctx:run(0x0116, (object) & 0xff)
end

-- 0x0117  Disables the given object.
ai.OPCODE["disable_object"] = 0x0117
function ai.disable_object(ctx, object)
  return ctx:run(0x0117, (object) & 0xff)
end

-- 0x0118  Sets a flag on the object's flags3 property (object struct offset 0x10).
ai.OPCODE["set_object_flag3"] = 0x0118
function ai.set_object_flag3(ctx, object, objectflag3)
  return ctx:run(0x0118, (object) & 0xff, u32(objectflag3))
end

-- 0x0119  Unsets a flag on the object's flags3 property.
ai.OPCODE["unset_object_flag3"] = 0x0119
function ai.unset_object_flag3(ctx, object, objectflag3)
  return ctx:run(0x0119, (object) & 0xff, u32(objectflag3))
end

-- 0x011A  Checks if the given object has the given flags3 property.
ai.OPCODE["if_object_flag3"] = 0x011A
function ai.if_object_flag3(ctx, object, objectflag3, label)
  return ctx:run(0x011A, (object) & 0xff, u32(objectflag3), (label) & 0xff)
end

-- 0x011B  Sets a flag on the given chr's hidden property (chr struct offset 0x14).
ai.OPCODE["set_chr_hiddenflag"] = 0x011B
function ai.set_chr_hiddenflag(ctx, chr, chrflag2)
  return ctx:run(0x011B, (chr) & 0xff, u32(chrflag2))
end

-- 0x011C  Unsets a flag on the given chr's hidden property.
ai.OPCODE["unset_chr_hiddenflag"] = 0x011C
function ai.unset_chr_hiddenflag(ctx, chr, chrflag2)
  return ctx:run(0x011C, (chr) & 0xff, u32(chrflag2))
end

-- 0x011D  Checks if the given chr has the given hidden flag.
ai.OPCODE["if_chr_has_hiddenflag"] = 0x011D
function ai.if_chr_has_hiddenflag(ctx, chr, chrflag2, label)
  return ctx:run(0x011D, (chr) & 0xff, u32(chrflag2), (label) & 0xff)
end

-- 0x011E  Checks if the given chr is human.
ai.OPCODE["if_chr_is_human"] = 0x011E
function ai.if_chr_is_human(ctx, chr, label)
  return ctx:run(0x011E, (chr) & 0xff, (label) & 0xff)
end

-- 0x011F  Checks if the given chr is Skedar.
ai.OPCODE["if_chr_is_skedar"] = 0x011F
function ai.if_chr_is_skedar(ctx, chr, label)
  return ctx:run(0x011F, (chr) & 0xff, (label) & 0xff)
end

-- 0x0120  Calculates a safety score based on several factors and compares it to the given value.
ai.OPCODE["if_calculated_safety2_lt"] = 0x0120
function ai.if_calculated_safety2_lt(ctx, value, label)
  return ctx:run(0x0120, (value) & 0xff, (label) & 0xff)
end

-- 0x0121  Finds cover using the given criteria.
ai.OPCODE["find_cover"] = 0x0121
function ai.find_cover(ctx, criteria, label)
  return ctx:run(0x0121, u16(criteria), (label) & 0xff)
end

-- 0x0122  
ai.OPCODE["find_cover_within_dist"] = 0x0122
function ai.find_cover_within_dist(ctx, criteria, distance, label)
  return ctx:run(0x0122, u16(criteria), u32(distance), (label) & 0xff)
end

-- 0x0123  
ai.OPCODE["find_cover_outside_dist"] = 0x0123
function ai.find_cover_outside_dist(ctx, criteria, distance, label)
  return ctx:run(0x0123, u16(criteria), u32(distance), (label) & 0xff)
end

-- 0x0124  
ai.OPCODE["go_to_cover"] = 0x0124
function ai.go_to_cover(ctx, speed)
  return ctx:run(0x0124, (speed) & 0xff)
end

-- 0x0125  Checks if the chr's cover is still out of sight of their target and updates a flag in the cover struct accordingly.
ai.OPCODE["check_cover_out_of_sight"] = 0x0125
function ai.check_cover_out_of_sight(ctx, label)
  return ctx:run(0x0125, (label) & 0xff)
end

-- 0x0126  Checks if the player is using the CMP150 or AR34.
ai.OPCODE["if_player_using_cmp150_or_ar34"] = 0x0126
function ai.if_player_using_cmp150_or_ar34(ctx, label)
  return ctx:run(0x0126, (label) & 0xff)
end

-- 0x0127  Tries to find a chr who meets some criteria and sets them as the current chr's target.
ai.OPCODE["set_target_to_enemy_on_same_floor"] = 0x0127
function ai.set_target_to_enemy_on_same_floor(ctx, label)
  return ctx:run(0x0127, (label) & 0xff)
end

-- 0x0128  Checks if there's an enemy within the range and sight, then sets the chr's target chr field to that enemy.
ai.OPCODE["if_enemy_distance_lt_and_los"] = 0x0128
function ai.if_enemy_distance_lt_and_los(ctx, distance, label)
  return ctx:run(0x0128, ((distance // 10)) & 0xff, (label) & 0xff)
end

-- 0x0129  Calculates a safety score based on several factors and compares it to the given value.
ai.OPCODE["if_calculated_safety_lt"] = 0x0129
function ai.if_calculated_safety_lt(ctx, score, label)
  return ctx:run(0x0129, (score) & 0xff, (label) & 0xff)
end

-- 0x012A  Checks if the distance change from the current chr to the chr's target has not changed by more than 50 units since 1 second ago.
ai.OPCODE["if_target_moving_slowly"] = 0x012A
function ai.if_target_moving_slowly(ctx, chr, label)
  return ctx:run(0x012A, (chr) & 0xff, (label) & 0xff)
end

-- 0x012B  Checks if the distance between the chr and their target has decreased by at least 50 units in the last second.
ai.OPCODE["if_target_moving_closer"] = 0x012B
function ai.if_target_moving_closer(ctx, label)
  return ctx:run(0x012B, (label) & 0xff)
end

-- 0x012C  Checks if the distance between the chr and their target has increased by at least 50 units in the last second.
ai.OPCODE["if_target_moving_away"] = 0x012C
function ai.if_target_moving_away(ctx, label)
  return ctx:run(0x012C, (label) & 0xff)
end

-- 0x012F  
ai.OPCODE["cmd012f"] = 0x012F
function ai.cmd012f(ctx)
  return ctx:run(0x012F)
end

-- 0x0130  Allows the current chr to say a semi-random statement from some predefined lists.
ai.OPCODE["say_quip"] = 0x0130
function ai.say_quip(ctx, player, quip, probability, soundgap, onlyifothers, special, textrow, colour)
  return ctx:run(0x0130, (player) & 0xff, (quip) & 0xff, (probability) & 0xff, (soundgap) & 0xff, (onlyifothers) & 0xff, (special) & 0xff, (textrow) & 0xff, (colour) & 0xff)
end

-- 0x0131  Increases the alertness value for other chrs in the current chr's squadron.
ai.OPCODE["increase_squadron_alertness"] = 0x0131
function ai.increase_squadron_alertness(ctx, value)
  return ctx:run(0x0131, (value) & 0xff)
end

-- 0x0132  Set the current chr's action.
ai.OPCODE["set_action"] = 0x0132
function ai.set_action(ctx, action, bool)
  return ctx:run(0x0132, (action) & 0xff, (bool) & 0xff)
end

-- 0x0133  This command looks for other nearby and eligible chrs and assigns them orders in order to assist the current chr in doing their action.
ai.OPCODE["set_team_orders"] = 0x0133
function ai.set_team_orders(ctx, orders, label)
  return ctx:run(0x0133, (orders) & 0xff, (label) & 0xff)
end

-- 0x0134  Checks if the current chr's orders equal the given value.
ai.OPCODE["if_orders_eq"] = 0x0134
function ai.if_orders_eq(ctx, action, label)
  return ctx:run(0x0134, (253) & 0xff, (action) & 0xff, (label) & 0xff)
end

-- 0x0135  Checks if the current chr has orders at all.
ai.OPCODE["if_has_orders"] = 0x0135
function ai.if_has_orders(ctx, label)
  return ctx:run(0x0135, (label) & 0xff)
end

-- 0x0136  If operation is 0, looks like the chr runs from their runfrompos property.
ai.OPCODE["retreat"] = 0x0136
function ai.retreat(ctx, speed, operation)
  return ctx:run(0x0136, (speed) & 0xff, (operation) & 0xff)
end

-- 0x0137  
ai.OPCODE["if_chr_in_squadron_doing_action"] = 0x0137
function ai.if_chr_in_squadron_doing_action(ctx, action, label)
  return ctx:run(0x0137, (action) & 0xff, (label) & 0xff)
end

-- 0x0138  Checks if the sound if finished in the given channel.
ai.OPCODE["if_sound_finished"] = 0x0138
function ai.if_sound_finished(ctx, channel, label)
  return ctx:run(0x0138, (channel) & 0xff, (label) & 0xff)
end

-- 0x0139  
ai.OPCODE["cmd0139"] = 0x0139
function ai.cmd0139(ctx, angle, u1, bool)
  return ctx:run(0x0139, u32(angle), (u1) & 0xff, (bool) & 0xff)
end

-- 0x013A  Set the current chr's chrpreset to an unalerted teammate.
ai.OPCODE["try_set_chrpreset_to_unalerted_teammate"] = 0x013A
function ai.try_set_chrpreset_to_unalerted_teammate(ctx, distance, label)
  return ctx:run(0x013A, (distance) & 0xff, (0) & 0xff, (label) & 0xff)
end

-- 0x013B  Set the current chr's squadron.
ai.OPCODE["set_squadron"] = 0x013B
function ai.set_squadron(ctx, id)
  return ctx:run(0x013B, (id) & 0xff)
end

-- 0x013C  Makes the current chr face their cover spot.
ai.OPCODE["face_cover"] = 0x013C
function ai.face_cover(ctx, label)
  return ctx:run(0x013C, (label) & 0xff)
end

-- 0x013D  Checks if there is a live grenade or explosion nearby.
ai.OPCODE["if_dangerous_object_nearby"] = 0x013D
function ai.if_dangerous_object_nearby(ctx, flags, label)
  return ctx:run(0x013D, (flags) & 0xff, (label) & 0xff)
end

-- 0x013E  Makes the chr run away from a live grenade.
ai.OPCODE["run_from_grenade"] = 0x013E
function ai.run_from_grenade(ctx)
  return ctx:run(0x013E)
end

-- 0x013F  Checks if the current chopper's weapons are armed.
ai.OPCODE["if_chopper_weapons_armed"] = 0x013F
function ai.if_chopper_weapons_armed(ctx, label)
  return ctx:run(0x013F, (label) & 0xff)
end

-- 0x0140  Checks if a hoverbot's next step is less than or greater than the given value.
ai.OPCODE["if_hoverbot_next_step"] = 0x0140
function ai.if_hoverbot_next_step(ctx, operator, step, label)
  return ctx:run(0x0140, (operator) & 0xff, (step) & 0xff, (label) & 0xff)
end

-- 0x0141  Shuffle a set of Investigation terminals.
ai.OPCODE["shuffle_investigation_terminals"] = 0x0141
function ai.shuffle_investigation_terminals(ctx, goodtag, badtag, pc1, pc2, pc3, pc4)
  return ctx:run(0x0141, (goodtag) & 0xff, (badtag) & 0xff, (pc1) & 0xff, (pc2) & 0xff, (pc3) & 0xff, (pc4) & 0xff, (0) & 0xff)
end

-- 0x0142  Takes the given object, looks at the pad ID that the object is sitting on, then uses a lookup table at g_InvestigationPadMap to decide which pad to set as th...
ai.OPCODE["set_pad_preset_to_investigation_terminal"] = 0x0142
function ai.set_pad_preset_to_investigation_terminal(ctx, object)
  return ctx:run(0x0142, (object) & 0xff, (0) & 0xff)
end

-- 0x0143  Sets the current chopper's weapons to armed.
ai.OPCODE["chopper_arm_weapons"] = 0x0143
function ai.chopper_arm_weapons(ctx)
  return ctx:run(0x0143)
end

-- 0x0144  Sets the current chopper's weapons to unarmed.
ai.OPCODE["chopper_unarm_weapons"] = 0x0144
function ai.chopper_unarm_weapons(ctx)
  return ctx:run(0x0144, (0) & 0xff)
  -- NOTE: operand(s) label could not be resolved to a parameter and
  -- are packed as 0; pass via ctx:run directly if you need them.
end

-- 0x0145  Rebuilds the list of teams containing chr IDs in each team.
ai.OPCODE["rebuild_teams"] = 0x0145
function ai.rebuild_teams(ctx)
  return ctx:run(0x0145)
end

-- 0x0146  Rebuilds the list of squadrons containing chr IDs in each squadron.
ai.OPCODE["rebuild_squadrons"] = 0x0146
function ai.rebuild_squadrons(ctx)
  return ctx:run(0x0146)
end

-- 0x0147  Checks if all chrs in the given squadron are dead.
ai.OPCODE["if_all_chrs_in_squadron_are_dead"] = 0x0147
function ai.if_all_chrs_in_squadron_are_dead(ctx, squadron, label)
  return ctx:run(0x0147, (squadron) & 0xff, (label) & 0xff)
end

-- 0x0148  Set the given chr to listening.
ai.OPCODE["chr_set_listening"] = 0x0148
function ai.chr_set_listening(ctx, chr, value)
  return ctx:run(0x0148, (chr) & 0xff, (value) & 0xff)
end

-- 0x0149  Checks if the given chr is listening.
ai.OPCODE["if_chr_listening"] = 0x0149
function ai.if_chr_listening(ctx, chr, listenvalue, checktype, label)
  return ctx:run(0x0149, (chr) & 0xff, (listenvalue) & 0xff, (checktype) & 0xff, (label) & 0xff)
end

-- 0x014A  Always goes to label.
ai.OPCODE["if_true"] = 0x014A
function ai.if_true(ctx, u1, u2, u3, label)
  return ctx:run(0x014A, (u1) & 0xff, (u2) & 0xff, (u3) & 0xff, (label) & 0xff)
end

-- 0x014B  Checks if the current chr is not listening (ie.
ai.OPCODE["if_not_listening"] = 0x014B
function ai.if_not_listening(ctx, label)
  return ctx:run(0x014B, (label) & 0xff)
end

-- 0x0152  Checks if the number of chrs in the given squadron is greater than the given value.
ai.OPCODE["if_num_chrs_in_squadron_gt"] = 0x0152
function ai.if_num_chrs_in_squadron_gt(ctx, value, squadron, label)
  return ctx:run(0x0152, (value) & 0xff, (squadron) & 0xff, (label) & 0xff)
end

-- 0x0157  Toggles tinted glass opaqueness/transparency.
ai.OPCODE["set_tinted_glass_enabled"] = 0x0157
function ai.set_tinted_glass_enabled(ctx, bool)
  return ctx:run(0x0157, (bool) & 0xff)
end

-- 0x015B  Plays the given track in isolation.
ai.OPCODE["play_track_isolated"] = 0x015B
function ai.play_track_isolated(ctx, id)
  return ctx:run(0x015B, (id) & 0xff)
end

-- 0x015C  Restarts the default tracks (primary and ambient, if any) from the beginning.
ai.OPCODE["play_default_tracks"] = 0x015C
function ai.play_default_tracks(ctx)
  return ctx:run(0x015C)
end

-- 0x0165  Checks if the chr injured their target.
ai.OPCODE["if_chr_injured_target"] = 0x0165
function ai.if_chr_injured_target(ctx, chr, label)
  return ctx:run(0x0165, (chr) & 0xff, (label) & 0xff)
end

-- 0x0166  Checks if the current chr's action is the given action.
ai.OPCODE["if_action_eq"] = 0x0166
function ai.if_action_eq(ctx, action, label)
  return ctx:run(0x0166, (label) & 0xff)
end

-- 0x0167  Makes the Extraction hovercopter fire a rocket from the given side.
ai.OPCODE["hovercopter_fire_rocket"] = 0x0167
function ai.hovercopter_fire_rocket(ctx, side)
  return ctx:run(0x0167, (side) & 0xff)
end

-- 0x0168  Checks if the chr's shield has been damaged since the last time it was checked.
ai.OPCODE["if_chr_shield_damaged"] = 0x0168
function ai.if_chr_shield_damaged(ctx, chr, label)
  return ctx:run(0x0168, (chr) & 0xff, (label) & 0xff)
end

-- 0x0169  
ai.OPCODE["if_chr_idle_action_eq"] = 0x0169
function ai.if_chr_idle_action_eq(ctx, action, label)
  return ctx:run(0x0169, (action) & 0xff, (label) & 0xff)
end

-- 0x016A  Checks if the chr's Y coordinate is greater than or less than the given value.
ai.OPCODE["if_chr_y"] = 0x016A
function ai.if_chr_y(ctx, chr, value, operator, label)
  return ctx:run(0x016A, (chr) & 0xff, u16(value), (operator) & 0xff, (label) & 0xff)
end

-- 0x016B  Play a sound from the given object repeatedly.
ai.OPCODE["play_repeating_sound_from_object"] = 0x016B
function ai.play_repeating_sound_from_object(ctx, channel, object, volchangetimer60, dist2, dist3)
  return ctx:run(0x016B, (channel) & 0xff, (object) & 0xff, u16(volchangetimer60), u16(dist2), u16(dist3))
end

-- 0x016C  
ai.OPCODE["noop016c"] = 0x016C
function ai.noop016c(ctx)
  return ctx:run(0x016C)
end

-- 0x016D  Add motion blur to the player.
ai.OPCODE["add_motion_blur"] = 0x016D
function ai.add_motion_blur(ctx, chr, value, bool)
  return ctx:run(0x016D, (chr) & 0xff, (value) & 0xff, (bool) & 0xff)
end

-- 0x016E  Damage or undamage the given chr by the given amount.
ai.OPCODE["damage_chr_by_amount"] = 0x016E
function ai.damage_chr_by_amount(ctx, chr, amount, operation)
  return ctx:run(0x016E, (chr) & 0xff, (amount) & 0xff, (operation) & 0xff)
end

-- 0x016F  Follow the label if the given chr is holding their original gun or never had a gun to begin with.
ai.OPCODE["if_has_gun"] = 0x016F
function ai.if_has_gun(ctx, chr, label)
  return ctx:run(0x016F, (chr) & 0xff, (0) & 0xff, (label) & 0xff)
end

-- 0x0170  If operation is 1, checks if the chr's dropped gun can be run to and follow the label if so.
ai.OPCODE["do_gun_command"] = 0x0170
function ai.do_gun_command(ctx, operation, label)
  return ctx:run(0x0170, (operation) & 0xff, (label) & 0xff)
end

-- 0x0171  Checks if the chr's distance to their dropped gun is less than the given value.
ai.OPCODE["if_distance_to_gun_lt"] = 0x0171
function ai.if_distance_to_gun_lt(ctx, distance, label)
  return ctx:run(0x0171, u16((distance // 10)), (label) & 0xff)
end

-- 0x0172  Makes the chr's gun disappear from the ground and gives it to the chr (when a guard drops their gun and picks it up).
ai.OPCODE["chr_recover_gun"] = 0x0172
function ai.chr_recover_gun(ctx, chr, label)
  return ctx:run(0x0172, (chr) & 0xff, (label) & 0xff)
end

-- 0x0173  Attempts to copy properties from the given chr to the current chr.
ai.OPCODE["try_inherit_properties"] = 0x0173
function ai.try_inherit_properties(ctx, chr_src, label)
  return ctx:run(0x0173, (chr_src) & 0xff, (label) & 0xff)
end

-- 0x0174  Checks if a controller button has been pressed during a cutscene.
ai.OPCODE["if_controller_button_pressed"] = 0x0174
function ai.if_controller_button_pressed(ctx, label)
  return ctx:run(0x0174, (label) & 0xff)
end

-- 0x0175  
ai.OPCODE["cmd0175"] = 0x0175
function ai.cmd0175(ctx, u1)
  return ctx:run(0x0175, (u1) & 0xff)
end

-- 0x0176  
ai.OPCODE["if_bot_respawning"] = 0x0176
function ai.if_bot_respawning(ctx, label)
  return ctx:run(0x0176, (label) & 0xff)
end

-- 0x0177  Forces the player to walk to the given pad (eg.
ai.OPCODE["force_walk"] = 0x0177
function ai.force_walk(ctx, chr, aimpad, walkspeed, turnspeed, lookup, dist)
  return ctx:run(0x0177, (chr) & 0xff, u16(aimpad), (walkspeed) & 0xff, (turnspeed) & 0xff, (lookup) & 0xff, (dist) & 0xff)
end

-- 0x0178  Checks if the player's force walk has finished.
ai.OPCODE["if_force_walk_finished"] = 0x0178
function ai.if_force_walk_finished(ctx, chr, label)
  return ctx:run(0x0178, (chr) & 0xff, (label) & 0xff)
end

-- 0x0179  
ai.OPCODE["play_sound_from_entity"] = 0x0179
function ai.play_sound_from_entity(ctx, channel, entity_id, u1, u2, attackflags)
  return ctx:run(0x0179, (channel) & 0xff, (entity_id) & 0xff, (0) & 0xff, (1) & 0xff, u16(u1), u16(u2), (attackflags) & 0xff)
end

-- 0x017A  Checks if the chr can see their attack target, which should have been specified in a prior attack command using attackflags and entityid.
ai.OPCODE["if_can_see_attack_target"] = 0x017A
function ai.if_can_see_attack_target(ctx, label)
  return ctx:run(0x017A, (label) & 0xff)
end

-- 0x017B  Checks if the chr is knocked out or invalid.
ai.OPCODE["if_chr_knockedout"] = 0x017B
function ai.if_chr_knockedout(ctx, chr, label)
  return ctx:run(0x017B, (chr) & 0xff, (label) & 0xff)
end

-- 0x017C  Assigns a sound to the given channel.
ai.OPCODE["assign_sound"] = 0x017C
function ai.assign_sound(ctx, sound, channel)
  return ctx:run(0x017C, u16(sound), (channel) & 0xff)
end

-- 0x017D  Plays the given track for the purpose of a cutscene.
ai.OPCODE["play_cutscene_track"] = 0x017D
function ai.play_cutscene_track(ctx, tracknum)
  return ctx:run(0x017D, (tracknum) & 0xff)
end

-- 0x017E  Stops the cutscene track and restarts the default tracks for the current stage.
ai.OPCODE["stop_cutscene_track"] = 0x017E
function ai.stop_cutscene_track(ctx)
  return ctx:run(0x017E)
end

-- 0x017F  Overrides the ambient track temporarily to the given one and plays it.
ai.OPCODE["play_temporary_track"] = 0x017F
function ai.play_temporary_track(ctx, tracknum)
  return ctx:run(0x017F, (tracknum) & 0xff)
end

-- 0x0180  Stops the ambient track.
ai.OPCODE["stop_ambient_track"] = 0x0180
function ai.stop_ambient_track(ctx)
  return ctx:run(0x0180)
end

-- 0x0181  Checks if the player is looking directly at the given object.
ai.OPCODE["if_chr_looking_at_object"] = 0x0181
function ai.if_chr_looking_at_object(ctx, chr, object, label)
  return ctx:run(0x0181, (chr) & 0xff, (object) & 0xff, (label) & 0xff)
end

-- 0x0182  Makes the current chr attack their target by punching or kicking.
ai.OPCODE["try_punch_or_kick"] = 0x0182
function ai.try_punch_or_kick(ctx, label)
  return ctx:run(0x0182, (0) & 0xff, (label) & 0xff)
end

-- 0x0183  Checks if the current chr's target is the player.
ai.OPCODE["if_target_is_player"] = 0x0183
function ai.if_target_is_player(ctx, label)
  return ctx:run(0x0183, (label) & 0xff)
end

-- 0x0184  Makes the chr begin the ACT_ATTACKAMOUNT action, although the specifics of this action are unknown.
ai.OPCODE["try_attack_amount"] = 0x0184
function ai.try_attack_amount(ctx, lower, upper)
  return ctx:run(0x0184, (lower) & 0xff, (upper) & 0xff)
end

-- 0x0185  
ai.OPCODE["mp_init_simulants"] = 0x0185
function ai.mp_init_simulants(ctx)
  return ctx:run(0x0185)
end

-- 0x0186  
ai.OPCODE["if_chr_soundtimer"] = 0x0186
function ai.if_chr_soundtimer(ctx, value, operator, label)
  return ctx:run(0x0186, u16(value), (operator) & 0xff, (label) & 0xff)
end

-- 0x0187  Checks if the current chr can see the player's camspy.
ai.OPCODE["set_target_to_camspy_if_in_sight"] = 0x0187
function ai.set_target_to_camspy_if_in_sight(ctx, label)
  return ctx:run(0x0187, (label) & 0xff)
end

-- 0x0188  Checks if the lift is currently stopped.
ai.OPCODE["if_lift_stationary"] = 0x0188
function ai.if_lift_stationary(ctx, lift, label)
  return ctx:run(0x0188, (lift) & 0xff, (label) & 0xff)
end

-- 0x0189  Makes the lift go to the given stop number.
ai.OPCODE["lift_go_to_stop"] = 0x0189
function ai.lift_go_to_stop(ctx, lift, stopnum)
  return ctx:run(0x0189, (lift) & 0xff, (stopnum) & 0xff)
end

-- 0x018A  Checks if the lift is stopped at the given stop number.
ai.OPCODE["if_lift_at_stop"] = 0x018A
function ai.if_lift_at_stop(ctx, lift, stopnum, label)
  return ctx:run(0x018A, (lift) & 0xff, (stopnum) & 0xff, (label) & 0xff)
end

-- 0x018B  Enables rain.
ai.OPCODE["enable_rain"] = 0x018B
function ai.enable_rain(ctx, value)
  return ctx:run(0x018B, (value) & 0xff)
end

-- 0x018C  Toggle the visibility of part of the chr's model.
ai.OPCODE["chr_toggle_modelpart"] = 0x018C
function ai.chr_toggle_modelpart(ctx, chr, modelpart)
  return ctx:run(0x018C, (chr) & 0xff, (modelpart) & 0xff)
end

-- 0x018D  Activate the given lift.
ai.OPCODE["activate_lift"] = 0x018D
function ai.activate_lift(ctx, liftid, object)
  return ctx:run(0x018D, (liftid) & 0xff, (object) & 0xff)
end

-- 0x018E  Makes a miniskedar attempt to pounce.
ai.OPCODE["miniskedar_try_pounce"] = 0x018E
function ai.miniskedar_try_pounce(ctx, u1, u2, label)
  return ctx:run(0x018E, (u1) & 0xff, u16(u2), (0) & 0xff, (label) & 0xff)
end

-- 0x018F  Checks if the distance between the given object and the given pad is less than the given value.
ai.OPCODE["if_object_distance_to_pad_lt"] = 0x018F
function ai.if_object_distance_to_pad_lt(ctx, object, distance, pad, label)
  return ctx:run(0x018F, (object) & 0xff, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x0190  Sets a savefile flag.
ai.OPCODE["set_savefile_flag"] = 0x0190
function ai.set_savefile_flag(ctx, flag)
  return ctx:run(0x0190, (flag) & 0xff)
end

-- 0x0191  Unsets a savefile flag.
ai.OPCODE["unset_savefile_flag"] = 0x0191
function ai.unset_savefile_flag(ctx, flag)
  return ctx:run(0x0191, (flag) & 0xff)
end

-- 0x0192  Checks if the given savefile flag is set.
ai.OPCODE["if_savefile_flag_is_set"] = 0x0192
function ai.if_savefile_flag_is_set(ctx, flag, label)
  return ctx:run(0x0192, (flag) & 0xff, (label) & 0xff)
end

-- 0x0193  Checks if the given savefile flag is unset.
ai.OPCODE["if_savefile_flag_is_unset"] = 0x0193
function ai.if_savefile_flag_is_unset(ctx, flag, label)
  return ctx:run(0x0193, (flag) & 0xff, (label) & 0xff)
end

-- 0x019E  Checks if the given object's health is less than the given value.
ai.OPCODE["if_object_health_lt"] = 0x019E
function ai.if_object_health_lt(ctx, object, value, label)
  return ctx:run(0x019E, (object) & 0xff, u16(value), (label) & 0xff)
end

-- 0x019F  Sets the given object's health.
ai.OPCODE["set_object_health"] = 0x019F
function ai.set_object_health(ctx, object, value)
  return ctx:run(0x019F, (object) & 0xff, u16(value))
end

-- 0x01A0  Assigns a special death animation to the given chr.
ai.OPCODE["set_chr_special_death_animation"] = 0x01A0
function ai.set_chr_special_death_animation(ctx, chr, specialdie)
  return ctx:run(0x01A0, (chr) & 0xff, (specialdie) & 0xff)
end

-- 0x01A1  Sets the current chr's roomtosearch field to the same room that the chr's target is in.
ai.OPCODE["set_chr_roomtosearch"] = 0x01A1
function ai.set_chr_roomtosearch(ctx)
  return ctx:run(0x01A1)
end

-- 0x01A2  Play a quip for the CI staff.
ai.OPCODE["play_cistaff_quip"] = 0x01A2
function ai.play_cistaff_quip(ctx, ciquip, channel)
  return ctx:run(0x01A2, (ciquip) & 0xff, (channel) & 0xff)
end

-- 0x01A3  If value is 0-2 or 4-14, do talking animation from a hard coded array.
ai.OPCODE["do_preset_animation"] = 0x01A3
function ai.do_preset_animation(ctx, value)
  return ctx:run(0x01A3, (value) & 0xff)
end

-- 0x01A4  Show or remove a HUD message.
ai.OPCODE["show_hudmsg_middle"] = 0x01A4
function ai.show_hudmsg_middle(ctx, operation, color, text)
  return ctx:run(0x01A4, (operation) & 0xff, (color) & 0xff, u16(text))
end

-- 0x01A5  Checks if the current chr is using a lift (most likely from the moment they call it until the moment the door opens at the end of the journey).
ai.OPCODE["if_using_lift"] = 0x01A5
function ai.if_using_lift(ctx, label)
  return ctx:run(0x01A5, (label) & 0xff)
end

-- 0x01A6  Checks if the Y distance between the current chr and their target is less than the given value.
ai.OPCODE["if_target_y_difference_lt"] = 0x01A6
function ai.if_target_y_difference_lt(ctx, distance, label)
  return ctx:run(0x01A6, ((distance // 10)) & 0xff, (label) & 0xff)
end

-- 0x01A7  Checks if the chr is not currently talking.
ai.OPCODE["if_chr_not_talking"] = 0x01A7
function ai.if_chr_not_talking(ctx, chr, label)
  return ctx:run(0x01A7, (chr) & 0xff, (label) & 0xff)
end

-- 0x01AA  
ai.OPCODE["cmd01aa"] = 0x01AA
function ai.cmd01aa(ctx, label)
  return ctx:run(0x01AA, (label) & 0xff)
end

-- 0x01AB  Checks if the number of knocked out chrs is less than or greater than the given value.
ai.OPCODE["if_num_subdued"] = 0x01AB
function ai.if_num_subdued(ctx, value, operator, label)
  return ctx:run(0x01AB, (value) & 0xff, ((1 - operator)) & 0xff, (label) & 0xff)
end

-- 0x01AD  Makes the player let go of the currently held object (eg.
ai.OPCODE["release_grabbed_object"] = 0x01AD
function ai.release_grabbed_object(ctx, chr)
  return ctx:run(0x01AD, (chr) & 0xff)
end

-- 0x01AE  Removes all items from the player's inventory.
ai.OPCODE["clear_inventory"] = 0x01AE
function ai.clear_inventory(ctx, chr)
  return ctx:run(0x01AE, (chr) & 0xff)
end

-- 0x01AF  Makes the player grab the given object (eg.
ai.OPCODE["grab_object"] = 0x01AF
function ai.grab_object(ctx, chr, object)
  return ctx:run(0x01AF, (chr) & 0xff, (object) & 0xff)
end

-- 0x01B1  Shuffles the pillars in Skedar Ruins.
ai.OPCODE["shuffle_ruins_pillars"] = 0x01B1
function ai.shuffle_ruins_pillars(ctx, pdst1, pdst2, pdst3, psrc1, psrc2, psrc3, psrc4, psrc5, mdst1, mdst2, mdst3, msrc1, msrc2, msrc3, msrc4, msrc5)
  return ctx:run(0x01B1, (pdst1) & 0xff, (pdst2) & 0xff, (pdst3) & 0xff, (psrc1) & 0xff, (psrc2) & 0xff, (psrc3) & 0xff, (psrc4) & 0xff, (psrc5) & 0xff, (mdst1) & 0xff, (mdst2) & 0xff, (mdst3) & 0xff, (msrc1) & 0xff, (msrc2) & 0xff, (msrc3) & 0xff, (msrc4) & 0xff, (msrc5) & 0xff)
end

-- 0x01B2  Set the wind speed, which controls how quickly clouds in the sky are moving.
ai.OPCODE["set_wind_speed"] = 0x01B2
function ai.set_wind_speed(ctx, speed)
  return ctx:run(0x01B2, (speed) & 0xff)
end

-- 0x01B3  Toggle which player (Bond or Coop) is referenced by the chr's CHR_P1P2 identifier.
ai.OPCODE["chr_toggle_p1p2"] = 0x01B3
function ai.chr_toggle_p1p2(ctx, chr)
  return ctx:run(0x01B3, (chr) & 0xff)
end

-- 0x01B4  
ai.OPCODE["cmd01b4_if_something"] = 0x01B4
function ai.cmd01b4_if_something(ctx, label)
  return ctx:run(0x01B4, (label) & 0xff)
end

-- 0x01B5  Sets the given chr's p1p2 value explicitly to the given p1p2_chr.
ai.OPCODE["chr_set_p1p2"] = 0x01B5
function ai.chr_set_p1p2(ctx, chr, p1p2_chr)
  return ctx:run(0x01B5, (chr) & 0xff, (p1p2_chr) & 0xff)
end

-- 0x01B6  Enables or disables the snow effect.
ai.OPCODE["enable_snow"] = 0x01B6
function ai.enable_snow(ctx, bool)
  return ctx:run(0x01B6, (bool) & 0xff)
end

-- 0x01B7  Cloak or uncloak the given chr.
ai.OPCODE["set_chr_cloaked"] = 0x01B7
function ai.set_chr_cloaked(ctx, chr, bool_enable, bool_unknown)
  return ctx:run(0x01B7, (chr) & 0xff, (bool_enable) & 0xff, (bool_unknown) & 0xff)
end

-- 0x01B8  Define the team that an autogun should shoot at.
ai.OPCODE["set_autogun_target_team"] = 0x01B8
function ai.set_autogun_target_team(ctx, object, team)
  return ctx:run(0x01B8, (object) & 0xff, (team) & 0xff)
end

-- 0x01B9  Shuffle the generator switches in Pelagic II.
ai.OPCODE["shuffle_pelagic_switches"] = 0x01B9
function ai.shuffle_pelagic_switches(ctx)
  return ctx:run(0x01B9)
end

-- 0x01BA  Makes the chr attempt to do a lying down attack.
ai.OPCODE["try_attack_lie"] = 0x01BA
function ai.try_attack_lie(ctx, attackflags, entity_id, label)
  return ctx:run(0x01BA, u16(attackflags), u16(entity_id), (label) & 0xff)
end

-- 0x01BB  
ai.OPCODE["noop01bb"] = 0x01BB
function ai.noop01bb(ctx)
  return ctx:run(0x01BB, u16(0))
end

-- 0x01BC  
ai.OPCODE["cmd01bc"] = 0x01BC
function ai.cmd01bc(ctx, u1, label)
  return ctx:run(0x01BC, (u1) & 0xff, (label) & 0xff)
end

-- 0x01BD  Checks if the CI training PC has been holographed.
ai.OPCODE["if_training_pc_holographed"] = 0x01BD
function ai.if_training_pc_holographed(ctx, label)
  return ctx:run(0x01BD, (label) & 0xff)
end

-- 0x01BE  Checks if the given player is using the given device.
ai.OPCODE["if_player_using_device"] = 0x01BE
function ai.if_player_using_device(ctx, player, weapon, label)
  return ctx:run(0x01BE, (player) & 0xff, (weapon) & 0xff, (label) & 0xff)
end

-- 0x01BF  Begins or ends the Deep Sea teleport effect.
ai.OPCODE["teleport_to_pad"] = 0x01BF
function ai.teleport_to_pad(ctx, pad, chr)
  return ctx:run(0x01BF, u16(pad), (chr) & 0xff)
end

-- 0x01C0  Checks if the teleport effect is full white.
ai.OPCODE["if_teleport_full_white"] = 0x01C0
function ai.if_teleport_full_white(ctx, label, chr)
  return ctx:run(0x01C0, (label) & 0xff, (chr) & 0xff)
end

-- 0x01C1  Sets the current chr's punchdodge ailist.
ai.OPCODE["set_aipunchdodgelist"] = 0x01C1
function ai.set_aipunchdodgelist(ctx, ailistid)
  return ctx:run(0x01C1, u16(ailistid))
end

-- 0x01C2  Sets the current chr's shootingatme ailist.
ai.OPCODE["set_aishootingatmelist"] = 0x01C2
function ai.set_aishootingatmelist(ctx, ailistid)
  return ctx:run(0x01C2, u16(ailistid))
end

-- 0x01C3  Sets the current chr's darkroom ailist.
ai.OPCODE["set_darkroomlist"] = 0x01C3
function ai.set_darkroomlist(ctx, ailist)
  return ctx:run(0x01C3, u16(ailist))
end

-- 0x01C4  Sets the current chr's playerdead ailist.
ai.OPCODE["set_aiplayerdeadlist"] = 0x01C4
function ai.set_aiplayerdeadlist(ctx, ailistid)
  return ctx:run(0x01C4, u16(ailistid))
end

-- 0x01C5  Makes the chr do an animation as if they are avoiding a projectile.
ai.OPCODE["avoid"] = 0x01C5
function ai.avoid(ctx)
  return ctx:run(0x01C5)
end

-- 0x01C6  Sets the current chr's dodgerating and maxdodgerating properties.
ai.OPCODE["set_chr_dodge_rating"] = 0x01C6
function ai.set_chr_dodge_rating(ctx, value, whichprop)
  return ctx:run(0x01C6, (value) & 0xff, (whichprop) & 0xff)
end

-- 0x01C7  This doesn't appear to be used.
ai.OPCODE["set_unarmeddodgerating"] = 0x01C7
function ai.set_unarmeddodgerating(ctx, value)
  return ctx:run(0x01C7, (value) & 0xff)
end

-- 0x01C8  Sets the title mode (legal, Rare logo, etc).
ai.OPCODE["title_init_mode"] = 0x01C8
function ai.title_init_mode(ctx, mode)
  return ctx:run(0x01C8, (mode) & 0xff)
end

-- 0x01C9  Exits the title screen.
ai.OPCODE["try_exit_title"] = 0x01C9
function ai.try_exit_title(ctx, label)
  return ctx:run(0x01C9, (label) & 0xff)
end

-- 0x01CA  Set a weapon to be used in a cutscene.
ai.OPCODE["set_cutscene_weapon"] = 0x01CA
function ai.set_cutscene_weapon(ctx, chr, weapon, weapon_fallback)
  return ctx:run(0x01CA, (chr) & 0xff, (weapon) & 0xff, (weapon_fallback) & 0xff)
end

-- 0x01CB  Fade the scene to the given color over the given number of frames.
ai.OPCODE["fade_to_color"] = 0x01CB
function ai.fade_to_color(ctx, rgba, num_frames)
  return ctx:run(0x01CB, u32(rgba), u16(num_frames))
end

-- 0x01CC  Checks if the screen fade is complete.
ai.OPCODE["if_fade_complete"] = 0x01CC
function ai.if_fade_complete(ctx, label)
  return ctx:run(0x01CC, (label) & 0xff)
end

-- 0x01CD  Determines whether Jo's HUD eyepiece thing is visible when in the third person perspective (ie.
ai.OPCODE["set_chr_hudpiece_visible"] = 0x01CD
function ai.set_chr_hudpiece_visible(ctx, chr, bool)
  return ctx:run(0x01CD, (chr) & 0xff, (bool) & 0xff)
end

-- 0x01CE  Disallows the use of weapons and unarmed.
ai.OPCODE["passive_mode"] = 0x01CE
function ai.passive_mode(ctx, bool)
  return ctx:run(0x01CE, (bool) & 0xff)
end

-- 0x01CF  Makes a chr start or stop shooting in a cutscene.
ai.OPCODE["set_chr_shooting_in_cutscene"] = 0x01CF
function ai.set_chr_shooting_in_cutscene(ctx, chr, bool)
  return ctx:run(0x01CF, (chr) & 0xff, (bool) & 0xff)
end

-- 0x01D0  
ai.OPCODE["set_portal_flag"] = 0x01D0
function ai.set_portal_flag(ctx, portal, flag)
  return ctx:run(0x01D0, u16(portal), (flag) & 0xff)
end

-- 0x01D1  Shows or hides part of the object's model.
ai.OPCODE["object_set_modelpart_visible"] = 0x01D1
function ai.object_set_modelpart_visible(ctx, object, modelpart, visible)
  return ctx:run(0x01D1, (object) & 0xff, (modelpart) & 0xff, (visible) & 0xff)
end

-- 0x01D2  Emits sparks from the given chr.
ai.OPCODE["emit_sparks"] = 0x01D2
function ai.emit_sparks(ctx, chr)
  return ctx:run(0x01D2, (chr) & 0xff)
end

-- 0x01D3  Sets the images for Dr Caroll.
ai.OPCODE["set_drcaroll_images"] = 0x01D3
function ai.set_drcaroll_images(ctx, chr, left, right)
  return ctx:run(0x01D3, (chr) & 0xff, (left) & 0xff, (right) & 0xff)
end

-- 0x01D4  
ai.OPCODE["set_room_flag"] = 0x01D4
function ai.set_room_flag(ctx, room, flag)
  return ctx:run(0x01D4, u16(room), u16(flag))
end

-- 0x01D5  Shows or hides non-essential chrs.
ai.OPCODE["show_nonessential_chrs"] = 0x01D5
function ai.show_nonessential_chrs(ctx, bool)
  return ctx:run(0x01D5, (bool) & 0xff)
end

-- 0x01D6  Configures the environment in some way.
ai.OPCODE["configure_environment"] = 0x01D6
function ai.configure_environment(ctx, room, operation, value)
  return ctx:run(0x01D6, u16(room), (operation) & 0xff, (value) & 0xff)
end

-- 0x01D7  Redundant command.
ai.OPCODE["if_distance_to_target2_lt"] = 0x01D7
function ai.if_distance_to_target2_lt(ctx, distance, label)
  return ctx:run(0x01D7, u16((distance // 10)), (label) & 0xff)
end

-- 0x01D8  Redundant command.
ai.OPCODE["if_distance_to_target2_gt"] = 0x01D8
function ai.if_distance_to_target2_gt(ctx, distance, label)
  return ctx:run(0x01D8, u16((distance // 10)), (label) & 0xff)
end

-- 0x01D9  
ai.OPCODE["play_sound_from_object2"] = 0x01D9
function ai.play_sound_from_object2(ctx, channel, object, sound, type, flags)
  return ctx:run(0x01D9, (channel) & 0xff, (object) & 0xff, u16(sound), (255) & 0xff, (255) & 0xff, (type) & 0xff, u16(flags))
end

-- 0x01DA  Unsure exactly how this works.
ai.OPCODE["play_music_continuously"] = 0x01DA
function ai.play_music_continuously(ctx, track)
  return ctx:run(0x01DA, (track) & 0xff)
end

-- 0x01DB  Kills the given chr.
ai.OPCODE["kill"] = 0x01DB
function ai.kill(ctx, chr)
  return ctx:run(0x01DB, (chr) & 0xff)
end

-- 0x01DC  Removes the given weapon from the current player's inventory.
ai.OPCODE["remove_weapon_from_inventory"] = 0x01DC
function ai.remove_weapon_from_inventory(ctx, weapon)
  return ctx:run(0x01DC, (weapon) & 0xff)
end

-- 0x01DD  Checks if the music engine's event queue is empty.
ai.OPCODE["if_music_event_queue_empty"] = 0x01DD
function ai.if_music_event_queue_empty(ctx, value, label)
  return ctx:run(0x01DD, (value) & 0xff, (label) & 0xff)
end

-- 0x01DE  Checks if the game is being played in co-operative mode.
ai.OPCODE["if_coop_mode"] = 0x01DE
function ai.if_coop_mode(ctx, label)
  return ctx:run(0x01DE, (label) & 0xff)
end

-- 0x01DF  Gets the distance from chr to pad, but only if they are on the same floor (ie.
ai.OPCODE["if_chr_same_floor_distance_to_pad_lt"] = 0x01DF
function ai.if_chr_same_floor_distance_to_pad_lt(ctx, chr, distance, pad, label)
  return ctx:run(0x01DF, (chr) & 0xff, u16((distance // 10)), u16(pad), (label) & 0xff)
end

-- 0x01E0  Clears references to the current chr.
ai.OPCODE["remove_references_to_chr"] = 0x01E0
function ai.remove_references_to_chr(ctx)
  return ctx:run(0x01E0)
end

return ai
